/*
 FusionCharts JavaScript Library - Gantt Chart
 Copyright FusionCharts Technologies LLP
 License Information at <http://www.fusioncharts.com/license>

 @version 3.7.1
*/
FusionCharts.register("module",["private","modules.renderer.js-gantt",function(){var W=this,K=W.hcLib,Ga=W.window,wa=/msie/i.test(Ga.navigator.userAgent)&&!Ga.opera,tb=K.chartAPI,Ra=K.chartAPI,gb=K.extend2,e=K.pluck,d=K.pluckNumber,ra=K.getFirstColor,Ha=K.graphics,ea=Ha.convertColor,hb=Ha.getDarkColor,jc=Ha.parseColor,Ea=K.parseUnsafeString,Ia=K.getFirstValue,ac=K.getValidValue,ka=K.Raphael,kc=K.COMMASTRING,Na=K.setLineHeight,Gb=K.getDashStyle,Hb=K.toRaphaelColor,Sa=K.each,lc=K.FC_CONFIG_STRING,Oa=
"rgba(192,192,192,"+(wa?.002:1E-6)+")",bc=Ha.mapSymbolName,wa=Math,Ja=wa.ceil,xa=wa.round,ha=wa.max,Fa=wa.min,cc=wa.abs,Ta=parseInt,Ib=parseFloat,mc={pageX:0,pageY:0},Z=K.plotEventHandler,pa,X,ub=K.hasTouch=void 0!==Ga.document.documentElement.ontouchstart,nc=K.addEvent,oc=K.removeEvent,Ua=function(b){return void 0!==b&&null!==b},Va={left:"start",right:"end",center:"middle"},ib={left:0,right:1,center:.5,undefined:.5},vb={top:1,bottom:0,middle:.5,undefined:.5},Wa={left:5,right:-5,center:0,undefined:0},
Ga=!/fusioncharts\.com$/i.test(Ga.location.hostname),Pa=function(b,a){this.min=b.min;this.max=d(b.visibleMax,b.max);this.pixelValueRatio=a/(this.max-this.min);this.startPixel=b.chart.marginLeft+b.chart.ganttStartX};Pa.prototype={getPixel:function(b){return this.startPixel+(b-this.min)*this.pixelValueRatio}};Pa.prototype.constructor=Pa;tb("gantt",{friendlyName:"Gantt Chart",rendererId:"gantt",standaloneInit:!0,defaultSeriesType:"gantt",canvasborderthickness:1,defaultPlotShadow:1,creditLabel:Ga,fireGroupEvent:!0,
defaultPaletteOptions:function(){var b=arguments;return K.extend2(K.extend2(K.extend2(K.extend2({},b[0]),b[1]),b[2]),b[3])}(gb({},K.defaultGaugePaletteOptions),{paletteColors:["AFD8F8 F6BD0F 8BBA00 FF8E46 008E8E D64646 8E468E 588526 B3AA00 008ED6 9D080D A186BE CC6600 FDC689 ABA000 F26D7D FFF200 0054A6 F7941C CC3300 006600 663300 6DCFF6".split(" "),"AFD8F8 F6BD0F 8BBA00 FF8E46 008E8E D64646 8E468E 588526 B3AA00 008ED6 9D080D A186BE CC6600 FDC689 ABA000 F26D7D FFF200 0054A6 F7941C CC3300 006600 663300 6DCFF6".split(" "),
"AFD8F8 F6BD0F 8BBA00 FF8E46 008E8E D64646 8E468E 588526 B3AA00 008ED6 9D080D A186BE CC6600 FDC689 ABA000 F26D7D FFF200 0054A6 F7941C CC3300 006600 663300 6DCFF6".split(" "),"AFD8F8 F6BD0F 8BBA00 FF8E46 008E8E D64646 8E468E 588526 B3AA00 008ED6 9D080D A186BE CC6600 FDC689 ABA000 F26D7D FFF200 0054A6 F7941C CC3300 006600 663300 6DCFF6".split(" "),"AFD8F8 F6BD0F 8BBA00 FF8E46 008E8E D64646 8E468E 588526 B3AA00 008ED6 9D080D A186BE CC6600 FDC689 ABA000 F26D7D FFF200 0054A6 F7941C CC3300 006600 663300 6DCFF6".split(" ")],
bgColor:["FFFFFF","FFFFFF","FFFFFF","FFFFFF","FFFFFF"],bgAngle:[270,270,270,270,270],bgRatio:["100","100","100","100","100"],bgAlpha:["100","100","100","100","100"],canvasBgColor:["FFFFFF","FFFFFF","FFFFFF","FFFFFF","FFFFFF"],canvasBgAngle:[0,0,0,0,0],canvasBgAlpha:["100","100","100","100","100"],canvasBgRatio:["","","","",""],canvasBorderColor:["545454","545454","415D6F","845001","68001B"],canvasBorderAlpha:[100,100,100,90,100],gridColor:["DDDDDD","D8DCC5","99C4CD","DEC49C","FEC1D0"],gridResizeBarColor:["999999",
"545454","415D6F","845001","D55979"],categoryBgColor:["F1F1F1","EEF0E6","F2F8F9","F7F0E6","FFF4F8"],dataTableBgColor:["F1F1F1","EEF0E6","F2F8F9","F7F0E6","FFF4F8"],toolTipBgColor:["FFFFFF","FFFFFF","FFFFFF","FFFFFF","FFFFFF"],toolTipBorderColor:["545454","545454","415D6F","845001","68001B"],baseFontColor:["555555","60634E","025B6A","A15E01","68001B"],borderColor:["767575","545454","415D6F","845001","68001B"],borderAlpha:[50,50,50,50,50],legendBgColor:["ffffff","ffffff","ffffff","ffffff","ffffff"],
legendBorderColor:["666666","545454","415D6F","845001","D55979"],plotBorderColor:["999999","8A8A8A","6BA9B6","C1934D","FC819F"],plotFillColor:["EEEEEE","D8DCC5","BCD8DE","E9D8BE","FEDAE3"],scrollBarColor:["EEEEEE","D8DCC5","99C4CD","DEC49C","FEC1D0"]}),charttopmargin:10,chartbottommargin:20,series:function(){var b=this.dataObj,a=b.chart,I=(I=b.categories)||[],c=I.length,q=this.hcJSON,k=q.chart,m=q[lc],z=this.smartLabel,f=this.colorManager,g=q.categories={},w=[],p=this.inCanvasStyle,t=this.numberFormatter,
D=Infinity,l=-Infinity,u=k.origW-k.marginLeft-k.marginRight,E=k.origH-k.marginTop-k.marginBottom,n=b.processes||{},h=n&&n.process,y=h&&h.length,x=Ta(p.fontSize,10),P=b.datatable,U=P&&P.datacolumn,G=U&&U.length,ga=b.connectors,M=ga&&ga.length,N=q.connectors=[],O=b.milestones&&b.milestones.milestone,C=O&&O.length,aa=q.milestone=[],H=b.tasks,ba=H&&H.task,L=ba&&ba.length,v=0,r=0,dc=d(a.forceganttwidthpercent,0),ca=0,Z=0,X=!1,ka={top:"top",bottom:"bottom"},B={top:"top",bottom:"bottom",undefined:"middle"},
S={right:"right",left:"left"},da={right:"right",left:"left",undefined:"center"},F=q.dataTable={},jb=Infinity,kb=-Infinity,pa=q.processIDMap=[],W,wa,Ga=d(a.dateintooltip,1),Ja=b.legend&&b.legend.item,Ha=q.tasksMap||(q.tasksMap={}),Pa=0,Ra=0,wb,Ba,Jb,Kb,lb,xb,Sa,Lb,Mb,sa,ya,Ca,Va,ib,Wa,Sb,yb,tb,za,qa,mb,R,Nb,Xa,Ya,Ob,Pb,Da,na,oa,Za,$a,ab,nb,bb,cb,Ka,La,ia,ub,Tb,ja,la,fa,ob,pb,db,V,J,Ub,eb,zb,Ma,Ab,Vb,Qb,qb,Wb,Bb,Cb,Db,Eb,Fb,Rb,rb,vb,ec,fc,gc,Qa,T,hc,ua,Q,Aa,ta,sb,ma,Xb,Yb,Zb,$b,va,fb,ic,A,Y;if(y){q.tasks=
[];delete q.yAxis;delete q.xAxis;k.backgroundColor=ea(e(a.bgcolor,"FFFFFF"),e(a.bgalpha,f.getColor("bgAlpha")));d(a.showborder,0)||(k.borderWidth=0);k.plotBorderColor=ea(e(a.canvasbordercolor,f.getColor("canvasBorderColor")),0===d(a.showcanvasborder,1)?0:e(a.canvasborderalpha,100));k.backgroundColor={FCcolor:{color:e(a.bgcolor,"FFFFFF"),alpha:e(a.bgalpha,f.getColor("bgAlpha")),angle:e(a.bgangle,f.getColor("bgAngle")),ratio:e(a.bgratio,f.getColor("bgRatio"))}};k.plotBackgroundColor={FCcolor:{color:e(a.canvasbgcolor,
f.getColor("canvasBgColor")),alpha:e(a.canvasbgalpha,f.getColor("canvasBgAlpha")),angle:e(a.canvasbgangle,f.getColor("canvasBgAngle")),ratio:e(a.canvasbgratio,f.getColor("canvasBgRatio"))}};k.plotBorderWidth=d(a.canvasborderthickness,1);k.outputDateFormat=e(a.outputdateformat,k.dateFormat);k.extendCategoryBg=d(a.extendcategorybg,0);k.ganttLineColor=ea(e(a.ganttlinecolor,f.getColor("gridColor")),d(a.ganttlinealpha,100));k.ganttLineThickness=d(a.ganttlinethickness,1);k.ganttLineDashStyle=d(a.ganttlinedashed,
0)?Gb(d(a.ganttlinedashlen,1),a.ganttlinedashgap,k.ganttLineThickness):"none";k.gridBorderColor=ea(e(a.gridbordercolor,f.getColor("gridColor")),d(a.gridborderalpha,100));k.gridBorderThickness=d(a.gridborderthickness,1);k.gridBorderDashStyle=d(a.gridborderdashed,0)?Gb(d(a.gridborderdashlen,1),a.gridborderdashgap,k.gridborderThickness):"none";k.showSlackAsFill=d(a.showslackasfill,1);k.slackFillColor=ra(e(a.slackfillcolor,"FF5E5E"));k.gridResizeBarColor=ea(e(a.gridresizebarcolor,f.getColor("gridResizeBarColor")),
d(a.gridresizebaralpha,100));k.gridResizeBarThickness=d(a.gridresizebarthickness,1);k.taskBarRoundRadius=d(a.taskbarroundradius,0);k.taskBarFillMix=a.taskbarfillmix;k.taskBarFillRatio=a.taskbarfillratio;void 0===k.taskBarFillMix&&(k.taskBarFillMix="{light-10},{dark-20},{light-50},{light-85}");void 0===k.taskBarFillRatio&&(k.taskBarFillRatio="0,8,84,8");k.connectorExtension=d(a.connectorextension,10);k.clickURL=e(a.clickurl,"");k.annRenderDelay=a.annrenderdelay;k.taskDatePadding=d(a.taskdatepadding,
3);k.taskLabelPadding=d(a.tasklabelspadding,2);k.ganttStartX=d(a.ganttwidthpercent,65);100<k.ganttStartX&&(k.ganttStartX=100);Ca=k.ganttStartX=.01*(100-k.ganttStartX)*u;k.gridWidth=u-k.ganttStartX;ic=d(a.showfulldatatable,1);db=n.width;db=d(k.ganttStartX*(/\%/g.test(db)&&.01*Ib(db,10))||db);Ca-=d(db,0);W=xa(db);Z+=1;for(A=0;A<G;A+=1)Lb=U[A].width,Mb=d(k.ganttStartX*(/\%/g.test(Lb)&&.01*Ib(Lb,10))||Lb),Ca-=d(Mb,0),Mb=U[A].width=xa(Mb),Z+=1;0<=Ca?Ca/=Z:(X=!0,Ca=k.ganttStartX/Z);if(dc||!ic)for((isNaN(W)||
X)&&(W=Ca),A=0;A<G;A+=1)(isNaN(U[A].width)||X)&&(U[A].width=Ca);for(A=0;A<c;A+=1){la=I[A];D=Infinity;l=-Infinity;ob=e(la.bgcolor,f.getColor("categoryBgColor"));pb=d(la.bgalpha,100);Za=e(la.font,p.fontFamily);$a=d(la.fontsize,x+1);ab=e(la.fontcolor,p.color);nb=d(la.isbold,1);bb=d(la.isitalic,0);cb=d(la.isunderline,0);d(la.verticalpadding,3);Ka=e(la.align,"center").toLowerCase();La=e(la.valign,"middle").toLowerCase();ub=(Tb=la.category)&&Tb.length;Qa=0;ma={};for(Y=0;Y<ub;Y+=1)ja=Tb[Y],na=t.getDateValue(ja.start).ms,
oa=t.getDateValue(ja.end).ms,isNaN(na)&&(na=void 0),na>l&&(l=na),na<=D&&(D=na),isNaN(oa)&&(oa=void 0),oa>l&&(l=oa),oa<=D&&(D=oa),ia=Ea(e(ja.label,ja.name)),T={color:ra(e(ja.fontcolor,ab)),fontFamily:e(ja.font,Za),fontSize:d(ja.fontsize,$a)+"px",fontWeight:d(ja.isbold,nb)&&"bold"||"normal",fontStyle:d(ja.isitalic,bb)&&"italic"||"normal",textDecoration:d(ja.isunderline,cb)&&"underline"||"none"},Na(T),z.setStyle(T),sa=z.getOriSize(ia),Qa=ha(Qa,sa.height),Q="FCCAT_"+A+"_"+Y,Jb=e(ja.hoverbandcolor,la.hoverbandcolor,
a.categoryhoverbandcolor,a.hoverbandcolor,f.getColor("gridColor")),Kb=d(ja.hoverbandalpha,la.hoverbandalpha,a.categoryhoverbandalpha,a.hoverbandalpha,30),lb=d(ja.showhoverband,la.showhoverband,a.showcategoryhoverband,a.showhoverband,a.showhovereffect,1),g[Q]={text:ia,style:T,start:na,end:oa,index:Y,isLast:A===c-1,bgColor:ea(e(ja.bgcolor,ob),d(ja.bgalpha,pb)),dimension:ma,link:ja.link,align:da[[e(ja.align,Ka).toLowerCase()]],vAlign:B[ka[e(ja.valign,La).toLowerCase()]],hoverColor:ea(Jb,Kb),useHover:lb,
usePlotHover:d(ja.showganttpanehoverband,la.showganttpanehoverband,a.showganttpaneverticalhoverband,lb)},g[Aa]&&(g[Aa].nextCol=g[Q],g[Q].prevCol=g[Aa]),Aa=Q;if(zb=g["FCCAT_"+A+"_0"])g[Q].first=zb,zb.last=g[Q],g[eb]&&(g[eb].nextRow=zb,zb.prevRow=g[eb]);eb=Q;ma.h=Qa+5+2*d(la.verticalpadding,3);ma.y=r;ma.min=D;ma.max=l;ma.numCat=Y;r+=ma.h;kb=ha(kb,l);jb=Fa(jb,D)}g.min=jb;g.max=kb;if(y){Qa=ya=0;fb="right"===e(n.positioningrid,"left").toLowerCase();T={color:ra(e(n.headerfontcolor,p.color)),fontFamily:e(n.headerfont,
p.fontFamily),fontSize:d(n.headerfontsize,x+3)+"px",fontWeight:d(n.headerisbold,1)&&"bold"||"normal",fontStyle:d(n.headerisitalic,0)&&"italic"||"normal",textDecoration:d(n.headerisunderline,0)&&"underline"||"none"};Na(T);ia=Ea(n.headertext);z.setStyle(T);sa=z.getOriSize(ia);ya=ha(ya,sa.width);Ka=da[S[e(n.headeralign,"center").toLowerCase()]];La=B[ka[e(n.headervalign,"middle").toLowerCase()]];ma={};Q=ta=eb="processHeader";F.processHeader={text:ia,style:T,align:Ka,vAlign:La,isHeader:!0,link:e(n.headerlink),
dimension:{x:0,w:0,h:ha(sa.height,r)},bgColor:ea(e(n.headerbgcolor,f.getColor("dataTableBgColor")),d(n.headerbgalpha,100)),key:Q,isLast:fb,drawResizer:!fb&&G,prevCol:null,nextCol:null,prevRow:null,nextRow:null};ob=e(n.bgcolor,f.getColor("dataTableBgColor"));pb=d(n.bgalpha,100);Za=e(n.font,p.fontFamily);$a=d(n.fontsize,x);ab=e(n.fontcolor,p.color);nb=d(n.isbold,0);bb=d(n.isitalic,0);cb=d(n.isunderline,0);Ka=e(n.align,"center").toLowerCase();La=e(n.valign,"middle").toLowerCase();for(A=0;A<y;A+=1)fa=
h[A],Jb=e(fa.hoverbandcolor,n.hoverbandcolor,a.processhoverbandcolor,a.hoverbandcolor,f.getColor("gridColor")),Kb=d(fa.hoverbandalpha,n.hoverbandalpha,a.processhoverbandalpha,a.hoverbandalpha,30),lb=d(fa.showhoverband,n.showhoverband,a.showprocesshoverband,a.showhoverband,a.showhovereffect,1),T={color:ra(e(fa.fontcolor,ab)),fontSize:d(fa.fontsize,$a)+"px",fontFamily:e(fa.font,Za),fontWeight:d(fa.isbold,nb)&&"bold"||"normal",fontStyle:d(fa.isitalic,bb)&&"italic"||"normal",textDecoration:d(fa.isunderline,
cb)&&"underline"||"none"},Na(T),ia=Ea(e(fa.label,fa.name)),z.setStyle(T),sa=z.getOriSize(ia),Qa=ha(Qa,sa.height),ya=ha(ya,sa.width),Aa=Q,Q=e(fa.id,"__FCDPID__"+A).toUpperCase(),F[Q]&&(Q="__FCDPID__"+A),pa[A]=Q,Ua(wb=d(fa.height,a.rowheight))&&(wb=cc(wb),Pa+=wb||0,Ra+=1),F[Q]={text:sa.text,style:T,link:fa.link,id:Q,processHeight:wb,labelHeight:sa.height,align:da[[e(fa.align,Ka).toLowerCase()]],vAlign:B[ka[e(fa.valign,La).toLowerCase()]],bgColor:ea(e(fa.bgcolor,ob),d(fa.bgalpha,pb)),prevCol:F[Aa],dimension:{},
hoverColor:ea(Jb,Kb),useHover:lb,usePlotHover:d(fa.showganttpanehoverband,n.showganttpanehoverband,a.showganttpanehorizontalhoverband,lb),isLast:fb,nextCol:null,prevRow:null,nextRow:null},F[Aa]&&(F[Aa].nextCol=F[Q]);F[Q].first=F[ta];F[ta].last=F[Q];F[ta].processCount=y;F[ta].countDefinedHeight=Ra;F[ta].totalHeight=Pa;wa=F[ta].maxProcessHeight=Qa+8;isNaN(W)&&(W=ya+10);ca+=W;ma.x=0;F[ta].dimension.w=ma.w=W;ma.h=wa=ha((E-F[ta].dimension.h)/y,wa)}fb&&(ca=0);if(G)for(q.datacolumns=[],A=0;A<G;A+=1){V=U[A];
ya=0;ob=ra(e(V.bgcolor,P.bgcolor,f.getColor("dataTableBgColor")));pb=d(V.bgalpha,P.bgalpha,100);Za=e(V.font,P.font,p.fontFamily);ab=ra(e(V.fontcolor,P.fontcolor,p.color));$a=d(V.fontsize,P.fontsize,x);nb=d(V.isbold,P.isbold,0);bb=d(V.isitalic,P.isitalic,0);cb=d(V.isunderline,P.isunderline,0);Ka=da[S[e(V.align,P.align,"center").toLowerCase()]];La=B[ka[e(V.valign,P.valign,"middle").toLowerCase()]];T={color:ra(e(V.headerfontcolor,P.headerfontcolor,ab)),fontFamily:e(V.headerfont,P.headerfont,Za),fontSize:d(V.headerfontsize,
P.headerfontsize,$a+3)+"px",fontWeight:d(V.headerisbold,P.headerisbold,1)&&"bold"||"normal",fontStyle:d(V.headerisitalic,P.headerisitalic,bb)&&"italic"||"normal",textDecoration:d(V.headerisunderline,P.headerisunderline,cb)&&"underline"||"none"};Na(T);ia=Ea(V.headertext);z.setStyle(T);sa=z.getOriSize(ia);ya=ha(ya,sa.width);Q=ta="_FCDtHeader_"+A;mb=F[Q]={text:ia,style:T,align:da[S[e(V.headeralign,P.headeralign,Ka).toLowerCase()]],vAlign:B[ka[e(V.headervalign,P.headervalign,La).toLowerCase()]],link:e(V.headerlink),
drawResizer:fb||A<G-1,dimension:{x:0+ca,w:V.width,h:F.processHeader&&F.processHeader.dimension.h},isHeader:!0,key:Q,bgColor:ea(e(V.headerbgcolor,P.headerbgcolor,f.getColor("dataTableBgColor")),d(V.headerbgalpha,P.headerbgalpha,100))};mb.data=[];hc=V.text||[];sb=F.processHeader;Ma=F[eb];Ma.nextRow=F[Q];F[Q].prevRow=Ma;sb=sb.nextCol;Ma=Ma.nextCol;ma={};eb=ta;for(Y=0;sb;sb=sb.nextCol,Ma=Ma.nextCol,Y+=1)Aa=Q,Q="_FCDt_"+A+"_"+Y,(ua=hc[Y])?(T={fontFamily:e(ua.font,Za),color:ra(e(ua.fontcolor,ab)),fontSize:d(ua.fontsize,
$a)+"px",fontWeight:d(ua.isbold,nb)&&"bold"||"normal",fontStyle:d(ua.isitalic,bb)&&"italic"||"normal",textDecoration:d(ua.isunderline,cb)&&"underline"||"none"},Na(T),z.setStyle(T),ia=Ea(ua.label),sa=z.getOriSize(ia),ya=ha(ya,sa.width),F[Q]={text:ia,style:T,link:e(ua.link,""),bgColor:ea(e(ua.bgcolor,ob),d(ua.bgalpha,pb)),align:da[S[e(ua.align,Ka).toLowerCase()]],vAlign:B[ka[e(ua.valign,La).toLowerCase()]],prevCol:F[Aa],dimension:ma,nextCol:null,nextRow:null,prevRow:null}):F[Q]={prevCol:F[Aa],dimension:ma,
isNaN:!0,nextCol:null,nextRow:null,prevRow:null},F[Aa].nextCol=F[Q],F[Q].prevRow=Ma,Ma.nextRow=F[Q],F[Q].hoverColor=F[pa[Y]].hoverColor,F[Q].useHover=F[pa[Y]].useHover,F[Q].usePlotHover=F[pa[Y]].usePlotHover;F[Q].first=F[ta];F[ta].last=F[Q];isNaN(V.width)?mb.width=ya+10:mb.width=V.width;ma.x=0+ca;ca+=F[ta].dimension.w=ma.w=mb.width;ma.h=wa;q.datacolumns.push(mb)}fb&&(fa=F.processHeader,fa.dimension.x=fa.nextCol.dimension.x=ca,ca+=W);dc||(k.ganttStartX=Fa(k.ganttStartX,ca));k.totalGridWidth=ca;Yb=
b.trendlines||{};q.trendlines=[];for(A=0;A<Yb.length;A+=1)for(C=(Zb=Yb[A].line)&&Zb.length,Y=0;Y<C;Y+=1)va=Zb[Y],$b=d(va.istrendzone,0),Da=e(va.color,f.getColor("legendBorderColor")),T=gb({},m.trendStyle),T.color=ea(Da),Na(T),q.trendlines.push({start:t.getDateValue(va.start).ms,end:t.getDateValue(va.end).ms,displayValue:Ea(e(va.displayvalue,va.start)),color:ea(Da,d(va.alpha,$b?40:99)),style:T,isTrendZone:$b,dashedStyle:d(va.dashed,0)?Gb(d(va.dashlen,3),d(va.dashgap,3),d(va.thickness,1)):"none",thickness:d(va.thickness,
1)});if(L){D=Infinity;l=-Infinity;d(a.taskbarroundradius,0);Ya=a.taskbarfillmix;Ob=a.taskbarfillratio;void 0===Ya&&(Ya="{light-10},{dark-20},{light-50},{light-85}");void 0===Ob&&(Ob="0,8,84,8");k.shadow=d(a.showshadow,1);Sa=d(a.showslackasfill,1);for(A=0;A<L;A+=1)J=ba[A],Ub=v%y,na=t.getDateValue(J.start).ms,oa=t.getDateValue(J.end).ms,Q=e(F[Ia(J.processid,"").toUpperCase()],F["__FCDPID__"+Ub],F[pa[Ub]]).id.toUpperCase(),Ab=d(J.alpha,H.alpha,100),Da=e(J.color,H.color,f.getColor("plotFillColor")),Qb=
d(J.borderalpha,H.borderalpha,100),Vb=e(J.bordercolor,H.bordercolor,f.getColor("plotBorderColor")),isNaN(na)&&(na=void 0),na>l&&(l=na),na<=D&&(D=na),isNaN(oa)&&(oa=void 0),oa>l&&(l=oa),oa<=D&&(D=oa),T={color:ra(e(J.fontcolor,H.fontcolor,p.color)),fontSize:d(J.fontsize,H.fontsize,x)+"px",fontFamily:e(J.font,H.font,p.fontFamily)},Na(T),v+=1,qb=f.parseColorMix(Da,Ya),Wb=f.parseAlphaList(Ab.toString(),qb.length),Bb=f.parseRatioList(Ob,qb.length),Cb=d(J.angle,H.angle,270),Rb=f.parseColorMix(e(J.slackfillcolor,
H.slackfillcolor,a.slackfillcolor,"FF5E5E"),Ya),rb=Fa(d(J.percentcomplete,-1),100),ia=Ia(e(J.label,J.name),""),Fb="",d(J.showlabel,J.showname,H.showlabels,H.showname,a.showtasklabels,a.showtasknames,0)&&(Fb=ia),d(J.showpercentlabel,H.showpercentlabel,a.showpercentlabel,0)&&-1!==rb&&(Fb+=" "+rb+"%"),vb={FCcolor:{color:qb.join(),alpha:Wb,ratio:Bb,angle:Cb}},Rb=Sa?{FCcolor:{color:Rb.join(),alpha:Wb,ratio:Bb,angle:Cb}}:Oa,ec={FCcolor:{color:f.parseColorMix(e(J.hoverfillcolor,H.hoverfillcolor,a.taskhoverfillcolor,
hb(Da,80)),Ya).join(),alpha:f.parseAlphaList(e(J.hoverfillalpha,H.hoverfillalpha,a.taskhoverfillalpha,Ab).toString(),qb.length),ratio:Bb,angle:Cb}},fc=ea(e(J.hoverbordercolor,H.hoverbordercolor,a.taskhoverbordercolor,hb(Vb,80)),e(J.hoverborderalpha,H.hoverborderalpha,a.taskhoverborderalpha,Qb)),gc=Sa?{FCcolor:{color:f.parseColorMix(hb(e(J.slackhoverfillcolor,H.slackhoverfillcolor,a.slackhoverfillcolor,a.slackfillcolor,"FF5E5E"),80),Ya).join(),alpha:f.parseAlphaList(e(J.slackhoverfillalpha,H.slackhoverfillalpha,
a.slackhoverfillalpha,Ab).toString(),qb.length),ratio:Bb,angle:Cb}}:Oa,Db=t.getFormattedDate(na),Eb=t.getFormattedDate(oa),Ba=ac(Ea(e(J.tooltext,J.hovertext,H.plottooltext,m.tooltext))),Ba=void 0!==Ba?K.parseTooltext(Ba,[3,28,29,30,31],{end:Eb,start:Db,label:ia,percentComplete:-1!==rb?t.percentValue(rb):"",processName:F[Q]&&F[Q].text},J):(""!==ia?ia+(Ga?", ":""):"")+(Ga?Db+" - "+Eb:""),Xa=Ia(J.id,"").toUpperCase(),Ha[Ia(Xa,A)]={dataObj:{processId:Q,label:Fb,labelAlign:da[[e(J.labelalign,a.tasklabelsalign,
"center").toLowerCase()]],link:J.link,start:na,end:oa,id:Ia(J.id,"").toUpperCase(),showAsGroup:d(J.showasgroup,0),animation:d(J.animation,a.animation,a.defaultanimation,1),style:T,percentComplete:rb,color:Hb(vb),slackColor:Hb(Rb),hoverFillColor:Hb(ec),hoverBorderColor:fc,slackHoverColor:Hb(gc),showHoverEffect:d(J.showhovereffect,H.showhovereffect,a.showtaskhovereffect,a.showhovereffect,1),shadow:{opacity:ha(Ab,Qb)/100,inverted:!0},borderColor:ea(Vb,Qb),borderThickness:d(J.showborder,H.showborder,
1)?d(J.borderthickness,H.borderthickness,1):0,height:e(J.height,"35%"),topPadding:e(J.toppadding,"35%"),showPercentLabel:d(J.showpercentlabel,H.showpercentlabel,a.showpercentlabel,0),startDate:d(J.showstartdate,H.showstartdate,a.showtaskstartdate)?Db:void 0,endDate:d(J.showenddate,H.showenddate,a.showtaskenddate)?Eb:void 0,toolText:Ba,_start:J.start,_end:J.end,_formatSDate:Db,_formatEDate:Eb,_label:ia}},w.push(Ha[Ia(Xa,A)].dataObj);kb=ha(kb,l);jb=Fa(jb,D)}q.series.push({showInLegend:!1,data:w});C=
O&&O.length;for(A=0;A<C;A+=1)R=O[A],Xa=Ia(R.taskid,"").toUpperCase(),Pb=e(R.shape,"polygon").toLowerCase(),Nb=d(R.numsides,5),Xb=0,"star"===Pb?Xb=.4:(Pb=bc(Nb),Pb=bc(Nb).split("-")[0]),Da=e(R.color,f.getColor("legendBorderColor")),Ba=ac(Ea(e(R.tooltext,R.hovertext,a.milestonetooltext))),void 0!==Ba&&Ha[Xa]?(J=Ha[Xa].dataObj,Ba=K.parseTooltext(Ba,[28,32,33,34,35,36],{date:t.getFormattedDate(R.date),taskStartDate:J._formatSDate,taskEndDate:J._formatEDate,taskLabel:J._label,taskPercentComplete:-1!==
J.percentComplete?t.percentValue(J.percentComplete):"",processName:F[J.processId]&&F[J.processId].text},R)):Ba=t.getFormattedDate(R.date),T={color:ra(e(R.fontcolor,a.milestonefontcolor,p.color)),fontSize:d(R.fontsize,a.milestonefontsize,x)+"px",fontFamily:e(R.font,a.milestonefont,p.fontFamily),fontWeight:d(R.fontbold,a.milestonefontbold,0)&&"bold"||"normal",fontStyle:d(R.fontitalic,a.milestonefontitalic,0)&&"italic"||"normal"},Na(T),aa.push({numSides:Nb,startAngle:d(R.startangle,90),radius:R.radius,
origDate:R.date,date:t.getDateValue(R.date),fillColor:ra(Da),fillAlpha:.01*d(R.fillalpha,R.alpha,100),borderColor:ra(e(R.bordercolor,Da)),borderAlpha:.01*d(R.borderalpha,R.alpha,100),displayValue:Ea(R.label),style:T,hoverFillColor:ra(e(R.hoverfillcolor,a.milestonehoverfillcolor,hb(Da,80))),hoverFillAlpha:.01*d(R.hoverfillalpha,a.milestonehoverfillalpha,R.fillalpha,R.alpha,100),hoverBorderColor:ra(e(R.hoverbordercolor,a.milestonehoverbordercolor,hb(e(R.bordercolor,Da),80))),hoverBorderAlpha:.01*d(R.hoverborderalpha,
a.milestonehoverborderalpha,R.borderalpha,R.alpha,100),showHoverEffect:d(R.showhovereffect,a.showmilestonehovereffect,a.showhovereffect,1),depth:Xb,taskId:Xa,borderThickness:d(R.borderthickness,1),link:R.link,toolText:Ba});for(A=0;A<M;A+=1)if(ib=(Va=(za=ga[A])&&za.connector)&&Va.length)for(Y=0;Y<ib;Y+=1)qa=Va[Y],Wa=e(qa.color,za.color,f.getColor("plotBorderColor")),Sb=d(qa.alpha,za.alpha,100),yb=d(qa.thickness,za.thickness,1),tb=d(qa.isdashed,za.isdashed,1),N.push({fromTaskId:Ia(qa.fromtaskid,"").toUpperCase(),
toTaskId:Ia(qa.totaskid,"").toUpperCase(),fromTaskConnectStart:d(qa.fromtaskconnectstart,0),toTaskConnectStart:d(qa.totaskconnectstart,1),color:ea(Wa),alpha:.01*Sb,link:qa.link,showHoverEffect:d(qa.showhovereffect,za.showhovereffect,a.showconnectorhovereffect,a.showhovereffect,1),hoverColor:ea(e(qa.hovercolor,za.hovercolor,a.connectorhovercolor,hb(Wa,80)),d(qa.hoveralpha,za.hoveralpha,a.connectorhoveralpha,Sb)),hoverThickness:d(qa.hoverthickness,za.hoverthickness,a.connectorhoverthickness,yb),thickness:yb,
dashedStyle:tb?Gb(d(qa.dashlen,za.dashlen,5),d(qa.dashgap,za.dashgap,yb),yb):"none"});q.legend.enabled=Boolean(d(a.showlegend,1));q.legend.interactiveLegend=!1;q.legend.itemStyle.cursor="default";q.legend.itemHoverStyle={cursor:"inherit"};C=Ja&&Ja.length;for(A=0;A<C;A+=1)xb=Ja[A],Ua(xb.label)&&""!==xb.label&&q.series.push({name:Ea(xb.label),showInLegend:!0,type:!1,color:jc(e(xb.color,f.getPlotColor()))});q.max=kb;q.min=jb;q.chart.hasScroll=!0;return q}},spaceManager:function(b,a,I,c){this.titleSpaceManager(b,
a,I,.3*c);var q=this.numberFormatter,k=b.chart,m=a.chart,z=b.dataTable,f=b.categories,g=b.scrollOptions={},w=z.__scrollOptions={},p=z.processHeader;c=c-k.marginTop-k.marginBottom;I=I-k.marginLeft-k.marginRight;var t=k.totalGridWidth,D=b.verticalScroll={enabled:d(m.useverticalscrolling,1)},l=d(m.ganttpaneduration,-1),u=e(m.ganttpanedurationunit,"s").toLowerCase(),E=q.getDateValue(m.scrolltodate).ms,n=p&&p.maxProcessHeight,h,y,q=0;if(p){h=p.processCount-p.countDefinedHeight;b.legend.enabled&&(c-=this.placeLegendBlockBottom(b,
a,I,c/2));c-=p.dimension.h;g.padding=d(m.scrollpadding,b.chart.plotBorderWidth/2);g.height=d(m.scrollheight,16);g.showButtons=!!d(m.scrollshowbuttons,1);g.buttonPadding=d(m.scrollbtnpadding,0);g.flatScrollBars=d(m.flatscrollbars,0);g.color=ra(e(m.scrollcolor,this.colorManager.getColor("altHGridColor")));a=g.height+g.padding;t>k.ganttStartX&&(w.enabled=!0,w.startPercent=Boolean(d(m.scrolltoend,0)));I-=k.ganttStartX;f.scroll={};g=new Date(f&&f.min);if(-1!==l){switch(u){case "y":g.setYear(g.getFullYear()+
l);break;case "m":g.setMonth(g.getMonth()+l);break;case "d":g.setDate(g.getDate()+l);break;case "h":g.setHours(g.getHours()+l);break;case "mn":g.setMinutes(g.getMinutes()+l);break;default:g.setSeconds(g.getSeconds()+l)}g=g.getTime();g>b.min&&g<b.max&&(b.visibleMax=g,f.scroll.enabled=!0)}if(w.enabled||f.scroll.enabled)c-=a;w=c-p.totalHeight;g=w/(h?h:p.processCount);!d(m.forcerowheight,0)&&!h&&p.totalHeight<c&&(g=c/p.processCount,w=c,y=!0);n>g&&(n=3>n-g?g:w/xa(w/n));p.maxProcessHeight=n;D.enabled&&
g<n&&h||0>g?(w=n,D.startPercent=Boolean(d(m.scrolltoend,0)),I-=a):(D.enabled=!1,w=g);f.scroll.startPercent=d(m.scrolltoend,0);if(Infinity===b.min||-Infinity===b.max||b.min===b.max)b.min=f.min=0,b.max=f.max=1;if(Infinity===f.min||-Infinity===f.max)f.min=b.min,f.max=b.max;f.axis=new Pa(b,I);f.startX=f.axis.getPixel(Fa(f.min,b.min));f.endX=f.axis.getPixel(ha(f.max,b.max));f.visibleW=I;E&&E>f.min&&E<f.max&&(f.scroll.startPercent=Fa((f.axis.getPixel(E)-f.startX)/(f.endX-f.startX-f.visibleW),1));for(p=
p.nextCol;p;){q+=p.dimension.h=y?w:p.processHeight||w;if(b=p.nextRow)for(;b;)b.dimension.h=p.dimension.h,b=b.nextRow;p=p.nextCol}z.processHeader.totalPH=q;k.processHeight=c+z.processHeader.dimension.h}}},tb.gaugebase);Ra("renderer.gantt",{drawProcess:function(b){var a=this,d=a.options,c=d.chart,q=a.paper,k=a.logic,m=k.smartLabel,z=a.canvasTop,f=a.canvasLeft,g=a.layers,w=g.gridLayer,p=g.gridHeaderLayer,t=c.gridBorderThickness,D=.5*t,l=c.gridBorderColor,u=c.gridBorderDashStyle,E=0,n=0,h=[],y=z,x=b.dimension.w||
16,P=b.dimension.x||0,U=d.dataTable.processHeader,G=U.nextCol.dimension.h,ga=U.totalPH,k=ea(e(k.dataObj.chart.rolloverbandcolor,"#FF0000"),e(k.dataObj.chart.rolloverbandalpha,30)),M=U.items||(U.items={}),d=d.categories||{},N,O,C,aa,H,ba,L,v,r,K,ca;M.hoverEle||(M.hoverEle=q.rect(d.startX,0,d.endX,G,0,g.dataset).attr({fill:k,visibility:"hidden","stroke-width":0}));r=function(b){Z.call(this,a,b,"ProcessClick")};K=function(b){pa=clearTimeout(pa);if(!X||X.removed)X=null;X&&a.gridOutHandler.call(X);a.gridHoverHandler.call(this);
Z.call(this,a,b,"ProcessRollOver")};for(ca=function(b){X=this;pa=clearTimeout(pa);pa=setTimeout(function(){a.gridOutHandler.call(X)},500);Z.call(X,a,b,"ProcessRollOut")};b;)v=b.dimension,L=f+P,C=b.text,C=b.align,M=b.items||(b.items={}),G=b.link,O=b.isHeader?p:w,aa=M.background,d=Ja(y+n)-.5,C={x:Ja(L+E)-.5,y:d,width:x+.5,height:v.h+D+.5,radius:0,fill:b.bgColor||Oa,"stroke-dasharray":u,stroke:l,cursor:G?"pointer":"","stroke-width":0},aa?aa.attr(C):(M.background=q.rect(O).attr(C).hover(K,ca),N={isHeader:b.isHeader,
label:b.text,vAlign:b.vAlign,align:b.align,link:b.link,id:b.id},M.background.click(r).data("dataObj",b).data("eventArgs",N).data("data",{y:d,gridObj:b,rollOverColor:k,useHover:!0,useNext:!0,height:v.h+D+.5,hoverEle:U.items.hoverEle})),b.isNaN||(v=b.dimension,C=b.text,C=b.align,aa=M.label,C=b.text,Ua(C)&&""!==C&&(ba=b.style,m.setStyle(ba),H=m.getSmartText(C,x-8,ha(Ta(ba.lineHeight,10),v.h)),ba.title=H.oriText,C=b.align,C={text:H.text,x:L+x*ib[C]+Wa[C],y:y+v.h-v.h*vb[b.vAlign],"text-anchor":Va[C],direction:c.textDirection,
cursor:G?"pointer":"","vertical-align":b.vAlign},aa?aa.attr(C):M.label=q.text(O).attr(C).css(ba).hover(K,ca).click(r).data("eventArgs",N).data("dataObj",b).data("data",{y:d,gridObj:b,rollOverColor:k,useHover:!0,height:v.h+D+.5,useNext:!0,hoverEle:U.items.hoverEle}))),b.xPos=L,b.yPos=Ja(y+v.h)-t%2*.5,h.push("M",L,b.yPos,"h",x),(aa=M.hBorder)?aa.attr("path",h):M.hBorder=q.path(h,O).attr({"stroke-dasharray":u,stroke:l,"stroke-width":t}),y+=v.h,b.nextCol||(E=D,n-=0,aa=b.first.items.vBorder,C=["M",Ja(L+
x)-t%2*.5,z,"v",ga],aa?aa.attr("path",C):b.first.items.vBorder=q.path(C,p).attr({"stroke-dasharray":u,stroke:l,"stroke-width":t}),b.nextRow&&!b.isLast&&(b.first.items.dragEle||(b.first.items.dragEle=q.path(C,g.gridTracker).attr({stroke:c.gridResizeBarColor,"stroke-width":c.gridResizeBarThickness,visibility:"hidden"})),b.first.items.tracker||(b.first.items.tracker=q.path(C,g.gridTracker).attr({stroke:Oa,ishot:!0,"stroke-width":30}).css("cursor",ka.svg&&"ew-resize"||"e-resize").drag(this.dragMove,this.dragStart,
this.dragUp).data("drag-options",{grid:b.first,xPos:Ja(L+x)-t%2*.5,chart:a})))),b=b.nextCol},dragStart:function(){var b=this.data("drag-options"),a=b.grid,I=a.items,c=a.nextRow,e={style:{lineHeight:16}},k=a.nextCol.style||e,m=c&&c.nextCol&&c.nextCol.style||e,z=b.chart,f=z.canvasLeft,g=a.dimension,k=ha(Ta(a.style.lineHeight,10),Ta(k.lineHeight,10))+2,e=ha(Ta((c||e).style.lineHeight,10),Ta(m.lineHeight,10))+2;b.leftSideLimit=f+d(a.dimension.x,0)+k;b.rightSideLimit=f+d(c&&c.dimension.x+c.dimension.w,
g.x+g.w)-e;b.origX=b.lastX||(b.lastX=0);I.dragEle.show();z.trackerClicked=!0;b.draged=!1},dragMove:function(b){var a=this.data("drag-options"),d=a.grid.items,c=a.xPos+b,e=a.leftSideLimit,k=a.rightSideLimit;c<e&&(b=e-a.xPos);c>k&&(b=k-a.xPos);c={transform:"t"+(a.origX+b)+kc+0};this.attr(c);d.dragEle.attr(c);a.draged=!0;a.lastX=b},dragUp:function(){var b=this.data("drag-options"),a=b.chart,d=b.grid,c=d.nextRow,e=a.canvasLeft,k=d.dimension,m=c&&c.dimension,z=d.items,f={hcJSON:{dataTable:{}}};a.trackerClicked=
!1;z.dragEle.hide();b.draged&&(k.w=b.xPos+b.lastX-e-k.x,d.nextCol&&(d.nextCol.dimension.w=k.w),f.hcJSON.dataTable[d.key]={dimension:k},c&&(m.w+=m.x-k.x-k.w,m.x=k.x+k.w,c.dimension.w=m.w,c.dimension.x=m.x,a.drawProcess(c),f.hcJSON.dataTable[c.key]={dimension:m}),a.drawProcess(d),gb(a.logic.chartInstance.jsVars._reflowData,f,!0),b.xPos+=b.lastX,b.lastX+=b.origX)},drawCategories:function(){var b=this,a=b.options,e=a.chart,c=b.paper,q=b.layers,k=b.logic.smartLabel,m=b.canvasTop,z=a.categories,f=a.dataTable.processHeader,
g=z.FCCAT_0_0,w=z.axis,p=z.endX,t=z.startX,D=p-t,l=e.ganttLineThickness,u=f.totalPH+f.dimension.h,E=[],n=[],h=q.dataset,q=q.ganttHeaderLayer,y,x,P,U,G,K,M,N,O,C,aa,H,ba,L,v;ba=function(a){Z.call(this,b,a,"CategoryClick")};L=function(a){pa=clearTimeout(pa);if(!X||X.removed)X=null;X&&b.gridOutHandler.call(X);b.gridHoverHandler.call(this);Z.call(this,b,a,"CategoryRollOver")};v=function(a){X=this;pa=clearTimeout(pa);pa=setTimeout(function(){b.gridOutHandler.call(X)},500);Z.call(X,b,a,"CategoryRollOut")};
U=z.items||(z.items={});f=a.dataTable.processHeader;for(U.hoverEle=c.rect(0,m+f.dimension.h,50,f.totalPH,0,h).attr({fill:Oa,visibility:"hidden","stroke-width":0});g;)x=D/g.dimension.numCat,G=t+x*(g.index+1),O=G-x,N=g.dimension.h,C=O,H=m+g.dimension.y,K=g.align,M=g.vAlign,P=g.link,U=g.items||(g.items={}),x=!(!g.nextRow&&g.nextCol),aa=a.verticalScroll.enabled&&x?a.scrollOptions.height:0,y={align:g.align,vAlign:g.vAlign,link:g.link,text:g.text},O=C=d(w.getPixel(g.start),O),G=d(w.getPixel(!x&&g.nextCol.start||
(x?ha(g.end||0,a.max):void 0)),G),x=G-O,C=xa(C)+.5,H=xa(H)+.5,g.isLast&&(E.push("M",C,H,"v",u-g.dimension.y),H-=.5*l,N-=l,e.extendCategoryBg&&c.rect(C,H,x,u,0,h).attr({fill:g.bgColor,"stroke-width":0,stroke:e.ganttLineColor}).toBack()),U.background=c.rect(C,H,x+aa,N,0,q).attr({fill:g.bgColor,"stroke-width":0,cursor:P?"pointer":"",stroke:e.ganttLineColor}).click(ba).data("eventArgs",y).data("dataObj",g).hover(L,v).data("data",{x:C,width:x,gridObj:g,hoverEle:z.items.hoverEle}),n.push("M",C,H,"v",N),
g.nextRow&&n.push("M",t,H+N,"H",p+aa),k.setStyle(g.style),G=k.getSmartText(g.text,x-5,N),g.style.title=G.oriText,U.label=c.text(q).attr({text:G.text,x:C+x*ib[K]+Wa[K],y:H+N-N*vb[M],"text-anchor":Va[K],cursor:P?"pointer":"",direction:e.textDirection,"vertical-align":M}).css(g.style).hover(L,v).click(ba).data("eventArgs",y).data("dataObj",g).data("data",{x:C,width:x,gridObj:g,hoverEle:z.items.hoverEle}),g=g.nextCol;for(;f;)E.push("M",z.startX,f.yPos,"H",p),f=f.nextCol;U=z.items||(z.items={});U.headerGrid=
c.path(n,q).attr({"stroke-dasharray":e.ganttLineDashStyle,"stroke-width":l,stroke:e.ganttLineColor});U.processGrid=c.path(E,h).attr({"stroke-dasharray":e.ganttLineDashStyle,"stroke-width":e.ganttLineThickness,stroke:e.ganttLineColor})},drawScroller:function(){var b=this,a=b.options,e=b.paper,c=b.layers,q=b.canvasTop,k=b.canvasHeight,m=a.scrollOptions,z=a.categories,f=z.startX,g=z.endX-f,w=m.flatScrollBars,p={hcJSON:{categories:{scroll:{}}}},t=c.dataset,D=c.datalabels,l=c.ganttTracker,u=c.ganttHeaderLayer,
E=b.logic.chartInstance&&b.logic.chartInstance.jsVars._reflowData||{},n=a.chart,h=c.gridLayer,y=(f=a.dataTable)&&f.processHeader,x=b.canvasLeft,P=b.canvasWidth,K=n.gridBorderThickness,G=n.totalGridWidth,ga=Fa(n.ganttStartX,G)+K,M=z.scroll,N=f&&f.__scrollOptions,O=a.verticalScroll,C={hcJSON:{dataTable:{__scrollOptions:{}},verticalScroll:{}}},aa=C.hcJSON.dataTable.__scrollOptions,H=y.totalPH,ba=c.gridHeaderLayer,L=c.gridTracker,v,r,f=d(z.startX,n.ganttStartX),c=c.scroll=c.scroll||e.group("scroll").insertAfter(l);
M.enabled&&(a=z.visibleW/g,M.scroller=e.scroller(f,q+k-m.height,z.visibleW,m.height,!0,{showButtons:m.showButtons,displayStyleFlat:w,buttonWidth:m.buttonWidth,scrollRatio:a,scrollPosition:M.startPercent},c).attr({"scroll-display-style":w,fill:m.color}).scroll(function(a){r=-xa(a*(g-z.visibleW));t&&t.transform(["T",r,t.data("vOffset")]);D&&D.transform(["T",r,D.data("vOffset")]);l&&l.transform(["T",r,l.data("vOffset")]);u&&u.transform(["T",r,0]);t&&t.data("hOffset",r);D&&D.data("hOffset",r);l&&l.data("hOffset",
r);p.hcJSON.categories.scroll.startPercent=a;gb(E,p,!0)}),function(){var a;ka.eve.on("raphael.scroll.start."+M.scroller.id,function(c){a=c;W.raiseEvent("scrollstart",{scrollPosition:c},b.logic.chartInstance)});ka.eve.on("raphael.scroll.end."+M.scroller.id,function(c){W.raiseEvent("scrollend",{prevScrollPosition:a,scrollPosition:c},b.logic.chartInstance)})}(),M.startPercent&&(r=-xa(M.startPercent*(g-z.visibleW)),t&&t.data("hOffset",r),D&&D.data("hOffset",r),l&&l.data("hOffset",r),u&&u.transform(["T",
r,0]),t&&t.transform(["T",r,t.data("vOffset")]),D&&D.transform(["T",r,t.data("vOffset")]),l&&l.transform(["T",r,t.data("vOffset")])));N.enabled&&(N.scroller=e.scroller(x,q+k-m.height,ga,m.height,!0,{showButtons:m.showButtons,displayStyleFlat:w,buttonWidth:m.buttonWidth,scrollRatio:ga/G,scrollPosition:N.startPercent},c).attr({"scroll-display-style":w,fill:m.color}).scroll(function(a){r=-xa(a*(G-ga));h&&h.transform(["T",r,h.data("vOffset")]);ba&&ba.transform(["T",r,0]);L&&L.transform(["T",r,L.data("vOffset")]);
h.data("hOffset",r);ba.data("hOffset",r);L.data("hOffset",r);aa.startPercent=a;gb(E,C,!0)}),function(){var a;ka.eve.on("raphael.scroll.start."+N.scroller.id,function(c){a=c;W.raiseEvent("scrollstart",{scrollPosition:c},b.logic.chartInstance)});ka.eve.on("raphael.scroll.end."+N.scroller.id,function(c){W.raiseEvent("scrollend",{prevScrollPosition:a,scrollPosition:c},b.logic.chartInstance)})}(),N.startPercent&&(r=-xa(N.startPercent*(G-ga)),h&&h.transform(["T",r,0]),L&&L.transform(["T",r,0]),ba&&ba.transform(["T",
r,0]),h.data("hOffset",r),L.data("hOffset",r)));O.enabled&&(v=n.processHeight-y.dimension.h,O.scroller=e.scroller(x+P-m.height,q+y.dimension.h,m.height,n.processHeight-y.dimension.h,!1,{showButtons:m.showButtons,displayStyleFlat:w,buttonWidth:m.buttonWidth,scrollRatio:v/H,scrollPosition:O.startPercent},c).attr({"scroll-display-style":w,fill:m.color}).scroll(function(a){r=-xa(a*(H-v));h&&h.transform(["T",h.data("hOffset"),r]);t&&t.transform(["T",t.data("hOffset"),r]);D&&D.transform(["T",D.data("hOffset"),
r]);l&&l.transform(["T",l.data("hOffset"),r]);L&&L.transform(["T",L.data("hOffset"),r]);h.data("vOffset",r);L.data("vOffset",r);t.data("vOffset",r);l.data("vOffset",r);D.data("vOffset",r);C.hcJSON.verticalScroll.startPercent=a;gb(E,C,!0)}),function(){var a;ka.eve.on("raphael.scroll.start."+O.scroller.id,function(c){a=c;W.raiseEvent("scrollstart",{scrollPosition:c},b.logic.chartInstance)});ka.eve.on("raphael.scroll.end."+O.scroller.id,function(c){W.raiseEvent("scrollend",{prevScrollPosition:a,scrollPosition:c},
b.logic.chartInstance)})}(),O.startPercent&&(r=-xa(O.startPercent*(H-v)),h&&h.transform(["T",h.data("hOffset"),r]),t&&t.transform(["T",t.data("hOffset"),r]),D&&D.transform(["T",D.data("hOffset"),r]),l&&l.transform(["T",l.data("hOffset"),r]),L&&L.transform(["T",L.data("hOffset"),r]),h.data("vOffset",r),L.data("vOffset",r),t.data("vOffset",r),D.data("vOffset",r),l.data("vOffset",r)))},finalizeScrollPlots:function(){var b=this,a=b.options,d=b.canvasTop,c=a.categories,e=c.endX,k=c.startX,m=c.scroll,z=
a.chart,f=a.dataTable,g=f&&f.processHeader,w=b.canvasLeft,p=z.gridBorderThickness,t=z.totalGridWidth,D=Fa(z.ganttStartX,t)+p,l,u,E,n,h,y=e-k-c.visibleW,e=b.container,x=f&&f.__scrollOptions,P=a.verticalScroll,U=g.totalPH,G=z.processHeight-g.dimension.h,ga,M,N,O,C,m=c.scroll,a=function(a){var e=b.elements.canvas,f=O.left,p=O.top,q=a.type,r=ub&&K.getTouchEvent(a)||mc,f=a.layerX||r.layerX||(a.pageX||r.pageX)-f;a=a.layerY||r.layerY||(a.pageY||r.pageY)-p;switch(q){case "dragstart":C=e.isPointInside(f,a);
ga=f>k&&f<k+c.visibleW;N=f>w&&f<k+c.visibleW&&a>d+g.dimension.h;M=f<k;l=C&&f||null;u=C&&a||null;break;case "dragend":C=!1;h=n=E=u=l=void 0;break;default:if(!C||b.trackerClicked)break;e=f-l;q=a-u;l=f;u=a;ga&&m&&m.scroller&&(E=m.scroller.attrs["scroll-position"]-e/y,m.scroller.attr({"scroll-position":E}));N&&P&&P.scroller&&(n=P.scroller.attrs["scroll-position"]-q/(U-G),P.scroller.attr({"scroll-position":n}));M&&x&&x.scroller&&(h=x.scroller.attrs["scroll-position"]-e/(t-D),x.scroller.attr({"scroll-position":h}))}};
ub&&(O=K.getPosition(e),e&&(oc(e,"dragstart drag dragend",a),nc(e,"dragstart drag dragend",a)))},gridHoverHandler:function(){var b=this.data("data"),a=b.gridObj,d=!!a.prevRow,c={};if(!a.isHeader)if(b.x&&(c.x=b.x),b.y&&(c.y=b.y),b.width&&(c.width=b.width),b.height&&(c.height=b.height),a.hoverColor&&(c.fill=a.hoverColor),a.usePlotHover&&b.hoverEle.attr(c).show(),b.useNext&&a.useHover){for(;a&&d;)a=a.prevRow,d=!!a.prevRow;for(;a;)a.items.background.attr("fill",a.hoverColor),a=a.nextRow}else a.useHover&&
a.items.background.attr("fill",a.hoverColor)},gridOutHandler:function(){var b=this.data("data"),a=b.gridObj,d=!!a.prevRow;if(!a.isHeader)if(a.usePlotHover&&b.hoverEle.hide(),b.useNext&&a.useHover){for(;a&&d;)a=a.prevRow,d=!!a.prevRow;for(;a;)a.items.background.attr("fill",a.bgColor||Oa),a=a.nextRow}else a.useHover&&a.items.background.attr("fill",a.bgColor)},drawAxes:function(){if(this.options.dataTable){Ra["renderer.cartesian"].drawAxes.call(this,arguments);var b=this.options,a=b.chart,e=this.paper,
c=this.layers,q=c.layerBelowDataset,k=c.layerAboveDataset,m=c.gridLayer,z=c.dataset,f=b.dataTable,g=b.categories,f=f&&f.processHeader,w=this.canvasTop,z=this.canvasLeft,m=a.gridBorderThickness,p=Fa(a.ganttStartX,a.totalGridWidth)+m,t=f.dimension,D=t.h,t=a.processHeight-t.h,l=d(g.startX,a.ganttStartX),g=g.visibleW,a=.5*a.ganttLineThickness,m=.5*m,m=c.gridLayer=c.gridLayer||e.group("grid",q).attr({"clip-rect":[z,w+D+m,p,t-m]});c.gridHeaderLayer=c.gridHeaderLayer||e.group("grid-header",q).attr({"clip-rect":[z,
w,p,D+t]});q=c.gridTracker=c.gridTracker||e.group("grid-tracker",q).attr({"clip-rect":[z,w,p,D+t]});m.data("vOffset",0);m.data("hOffset",0);q.data("vOffset",0);q.data("hOffset",0);c.ganttHeaderLayer=c.ganttHeaderLayer||e.group("gantt",k).attr({"clip-rect":[l,w,g+(b.verticalScroll.enabled?b.scrollOptions.height:0),this.chartHeight]});b=c.ganttTracker=e.group("gantt-hot",c.tracker).attr({"clip-rect":[l,w+D-a,g,t+a]});ka.svg?(z=c.dataset.attr({"clip-rect":[l,w+D-a,g,t+a]}),c=c.datalabels.attr({"clip-rect":[l,
w+D-a-10,g,t+a+10]})):z=c.dataset=c=c.datalabels=b=c.ganttTracker;z.data("vOffset",0);z.data("hOffset",0);c.data("vOffset",0);c.data("hOffset",0);b.data("vOffset",0);for(b.data("hOffset",0);f;)this.drawProcess(f),f=f.nextRow;this.drawCategories()}},drawPlotGantt:function(b){var a=this,I=a.options,c=I.chart,q=a.paper,k=a.layers,m=b.data,z=b.items,f=m.length,g=k.dataset,w=k.datalabels,p=I.dataTable,t=p.processHeader,D=I.categories,l=D.axis,u=a.canvasTop,E=c.taskBarRoundRadius,f=I.plotOptions.series,
n=isNaN(+f.animation)&&f.animation.duration||1E3*f.animation,h=I.tasksMap||(I.tasksMap={}),y=I.milestone,x=I.trendlines,P=t.dimension.h,K=c.taskDatePadding,G,ga,M,N,O,C,aa,H,ba,L,v,r,X,ca,ea,W,ha,B,S,da,F;b.graphics=[];ea=g.shadows||(g.shadows=q.group("shadows",g));f=x&&x.length;for(b=0;b<f;b+=1)v=x[b],v.end||(v.end=v.start),v.end&&(S=l.getPixel(v.start),W=l.getPixel(v.end),da=v.thickness,I=v.items||(v.items={}),G=void 0,v.isTrendZone?(L=["M",S+.5*(W-S),u+P,"v",u+t.totalPH],da=W-S):(L=["M",S,u+P,
"L",W,u+P+t.totalPH],G=v.dashedStyle),I.trendLine=q.path(L,g).attr({stroke:v.color,"stroke-width":da,"stroke-dasharray":G}),Ua(v.displayValue)&&""!==v.displayValue&&(I.label=q.text(k.ganttHeaderLayer).attr({text:v.displayValue,direction:c.textDirection,x:L[1],y:0}).css(v.style),G=I.label._getBBox().height,v=u+c.processHeight+(!D.scroll.enabled||c.marginBottom<G?.5*G:-(.5*G)-5),I.label.attr("y",v)));w.hide();k=function(){w.show()};x=t=function(b){Z.call(this,a,b)};D=function(b){Z.call(this,a,b,"DataPlotRollOver")};
u=function(b){Z.call(this,a,b,"DataPlotRollOut")};P=function(b){b&&b.click(function(b){Z.call(this,a,b)}).hover(function(b){var c=this.data("dataObj");Z.call(this,a,b,"DataPlotRollOver");c.showHoverEffect&&a.taskHoverHandler.call(this,a)},function(b){var c=this.data("dataObj");Z.call(this,a,b,"DataPlotRollOut");c.showHoverEffect&&a.taskHoverOutHandler.call(this,a)}).data("dataObj",B).data("eventArgs",ga)};f=m.length;for(b=0;b<f;b+=1)B=m[b],I=B.processId,v=p[I],W=ha=B.color,I=B.items||(B.items={}),
L=B.animation?n||1E3:0,v&&(F=B.borderThickness,S=xa(l.getPixel(B.start)),da=cc(N=l.getPixel(B.end)-S),S&&da&&(M=v.dimension.h,v=v.yPos-M,G=M*(/%/g.test(B.height)&&.01*Ib(B.height,10))||d(B.height,M),r=M*(/%/g.test(B.topPadding)&&.01*Ib(B.topPadding,10))||d(B.topPadding,M),v+=Fa(r,M-G),ca=.5*G,X=B.toolText,r=B.link,(M=z[b])||(M=z[b]={index:b,dataLabel:null,start:B.start,end:B.end,startLabel:null,endLabel:null,tracker:null}),B.index=b,O=e(B.id,b),""!==O&&h[O]&&(h[O].items=M,h[O].x=S,h[O].y=v,h[O].h=
G,h[O].w=da),N=O=C=aa=H=ba=null,B.showAsGroup?(L?(N=q.path(["M",S,v],g),N.animate({path:["M",S,v,"v",G,"L",S+ca,v+ca,"H",S+da-ca,"L",S+da,v+G,"v",-G,"H",S]},L,"normal",k)):(N=q.path(["M",S,v,"v",G,"L",S+ca,v+ca,"H",S+da-ca,"L",S+da,v+G,"v",-G,"H",S],g),k&&k()),N.attr({fill:W,stroke:B.borderColor,cursor:r?"pointer":"",ishot:!0,"stroke-width":B.borderThickness}).tooltip(X).shadow(c.shadow&&B.shadow,ea)):(-1!==B.percentComplete&&(N=da*B.percentComplete*.01,W=Oa,O=I.taskFill=q.rect(S,v,0,G,0,g).attr({fill:ha,
cursor:r?"pointer":"",ishot:!0,"stroke-width":0,width:L?0:N||1}).tooltip(X),L&&O.animate({width:N||1},L,"normal"),C=q.rect(S,v,0,G,0,g).attr({fill:B.slackColor,cursor:r?"pointer":"",ishot:!0,"stroke-width":0,x:L?S:S+N||1,width:L?0:da-N||1}).tooltip(X),L&&C.animate({x:S+N||1,width:da-N||1},L,"normal")),I=ka.crispBound(S,v,da,G,F),N=q.rect(I.x,I.y,0,I.height,E,g).attr({fill:W,stroke:B.borderColor,cursor:r?"pointer":"",ishot:!0,"stroke-width":B.borderThickness,width:L?0:I.width||1}).tooltip(X).shadow(c.shadow&&
B.shadow,ea),L?N.animate({width:I.width||1},L,"normal",k):k&&k()),Ua(B.label)&&""!==B.label&&(I=B.labelAlign,aa=q.text().attr({text:B.label,x:S+da*ib[I]+Wa[I],"text-anchor":Va[I],direction:c.textDirection,cursor:r?"pointer":"",ishot:!0,y:v-.5*Ta(B.style.lineHeight,10)-c.taskLabelPadding}).css(B.style),w.appendChild(aa)),Ua(B.startDate)&&""!==B.startDate&&(H=q.text().attr({text:B.startDate,x:S-2-K,y:v+.5*G,cursor:r?"pointer":"",ishot:!0,direction:c.textDirection,"text-anchor":"end"}).css(B.style),
w.appendChild(H)),Ua(B.endDate)&&""!==B.endDate&&(ba=q.text().attr({text:B.endDate,x:S+da+2+K,y:v+.5*G,cursor:r?"pointer":"",ishot:!0,direction:c.textDirection,"text-anchor":"start"}).css(B.style),w.appendChild(ba)),M.graphic=N,M.percentCompleteGraphic=O,M.slackGraphic=C,M.dataLabel=aa,M.startLabel=H,M.endLabel=ba,ga={processId:B.processId,taskId:B.id,start:B._start,end:B._end,showAsGroup:B.showAsGroup,link:B.link,sourceType:"task",percentComplete:-1!==B.percentComplete&&B.percentComplete},O&&O.click(t).hover(D,
u).data("eventArgs",ga),C&&C.click(x).data("eventArgs",ga),Sa([N,aa,H,ba],P)));p=function(b){Z.call(this,a,b,"MilestoneClick")};E=function(b){var c=this.data("dataObj");Z.call(this,a,b,"MilestoneRollOver");c.showHoverEffect&&c.items.graphic.attr({fill:c.hoverFillColor,stroke:c.hoverBorderColor,"fill-opacity":c.hoverFillAlpha,"stroke-opacity":c.hoverBorderAlpha})};K=function(b){var c=this.data("dataObj");Z.call(this,a,b,"MilestoneRollOut");c.showHoverEffect&&c.items.graphic.attr({fill:c.fillColor,
stroke:c.borderColor,"fill-opacity":c.fillAlpha,"stroke-opacity":c.borderAlpha})};this.drawConnectors();I=null;f=y&&y.length;for(b=0;b<f;b+=1)m=y[b],v=h[m.taskId],I=m.items||(m.items={}),v&&(z=ka.animation({"fill-opacity":m.fillAlpha,"stroke-opacity":m.borderAlpha},n,"normal"),ga={sides:m.sides,date:m.origDate,radius:m.radius,taskId:m.taskId,toolText:m.toolText,link:m.link,numSides:m.numSides},I.graphic=q.polypath(m.numSides,l.getPixel(m.date.ms),v.y+.5*v.h,d(m.radius,.6*v.h),m.startAngle,m.depth,
g).attr({fill:m.fillColor,"fill-opacity":n?0:m.fillAlpha,stroke:m.borderColor,"stroke-opacity":n?0:m.borderAlpha,groupId:"gId"+b,ishot:!0,cursor:m.link?"pointer":"","stroke-width":m.borderThickness}).tooltip(m.toolText).click(p).data("eventArgs",ga).data("dataObj",m),I.label=q.text().attr({text:m.displayValue,x:l.getPixel(m.date.ms),y:v.y+.5*v.h,groupId:"gId"+b,cursor:m.link?"pointer":"",ishot:!0,direction:c.textDirection,"text-anchor":"middle"}).css(m.style).tooltip(m.toolText).click(p).data("eventArgs",
ga).data("dataObj",m),w.appendChild(I.label),n&&I.graphic.animate(z.delay(n)),I.graphic.hover(E,K),I.label.hover(E,K))},taskHoverOutHandler:function(b){var a=b.options.tasksMap;b=this.data("dataObj");var a=a[e(b.id,b.index)].items,d={fill:b.color,stroke:b.borderColor,"stroke-width":b.borderThickness,"stroke-dasharray":b.dashedStyle};-1===b.percentComplete||b.showAsGroup||(a.slackGraphic.attr({fill:b.slackColor}),a.percentCompleteGraphic.attr({fill:b.color}),delete d.fill);a.graphic.attr(d)},taskHoverHandler:function(b){var a=
b.options.tasksMap;b=this.data("dataObj");var a=a[e(b.id,b.index)].items,d={fill:b.hoverFillColor,stroke:b.hoverBorderColor};-1===b.percentComplete||b.showAsGroup||(a.slackGraphic.attr({fill:b.slackHoverColor}),a.percentCompleteGraphic.attr({fill:b.hoverFillColor}),delete d.fill);a.graphic.attr(d)},drawConnectors:function(){var b=this,a=b.paper,d=b.options,c=d.chart.connectorExtension,e=d.connectors,k=d.tasksMap,m=e.length,z=b.layers.dataset,f=[],d=d.plotOptions.series,d=isNaN(+d.animation)&&d.animation.duration||
1E3*d.animation,g,w,p,t,D,l,u,E,n,h,y,x,K,U,G;K=function(a){Z.call(this,b,a,"ConnectorClick")};U=function(a){var c=this.data("dataObj"),d=k[c.fromTaskId],e=k[c.toTaskId],f={stroke:c.hoverColor,"stroke-dasharray":c.dashedStyle,"stroke-width":c.hoverThickness};Z.call(this,b,a,"ConnectorRollOver");c.showHoverEffect&&(Sa([d,e],function(a){var b={fill:a.dataObj.hoverFillColor,stroke:a.dataObj.hoverBorderColor};-1===a.dataObj.percentComplete||a.dataObj.showAsGroup||(a.items.slackGraphic.attr({fill:a.dataObj.slackHoverColor}),
a.items.percentCompleteGraphic.attr({fill:a.dataObj.hoverFillColor,stroke:a.dataObj.hoverBorderColor}),delete b.fill);a.items.graphic.attr(b)}),c.items.connector.attr(f))};G=function(a){var c=this.data("dataObj"),d=k[c.fromTaskId],e=k[c.toTaskId],f={stroke:c.color,"stroke-width":c.thickness,"stroke-dasharray":c.dashedStyle};Z.call(this,b,a,"ConnectorRollOut");c.showHoverEffect&&(Sa([d,e],function(a){var b={fill:a.dataObj.color,stroke:a.dataObj.borderColor,"stroke-width":a.dataObj.borderThickness,
"stroke-dasharray":a.dataObj.dashedStyle};-1===a.dataObj.percentComplete||a.dataObj.showAsGroup||(a.items.slackGraphic.attr({fill:a.dataObj.slackColor}),a.items.percentCompleteGraphic.attr({fill:a.dataObj.color}),delete b.fill);a.items.graphic.attr(b)}),c.items.connector.attr(f))};for(g=0;g<=m;g+=1)if(p=e[g]||{},l=p.fromTaskId,t=p.toTaskId,w=k[l],n=k[t],t=p.items||(p.items={}),w&&n){h=w.y+.5*w.h;y=n.y+.5*n.h;D=h==y;l=w.x;u=w.x+w.w;E=n.x;n=n.x+n.w;x=x=0;0===p.fromTaskConnectStart&&1===p.toTaskConnectStart&&
(x=1);0===p.fromTaskConnectStart&&0===p.toTaskConnectStart&&(x=2);1===p.fromTaskConnectStart&&1===p.toTaskConnectStart&&(x=3);1===p.fromTaskConnectStart&&0===p.toTaskConnectStart&&(x=4);if(D)switch(w=w.height,x){case 1:x=(E-u)/10;f=["M",u,h,u+x,h,"L",u+x,h,u+x,h-w,"L",u+x,h-w,E-x,h-w,"L",E-x,h-w,E-x,h,"L",E-x,h,E,y,"L",n+c,y,n,y];break;case 2:f=["M",u,h,u+c,h,"L",u+c,h,u+c,h-w,"L",u+c,h-w,n+c,h-w,"L",n+c,y-w,n+c,y];break;case 3:f=["M",l,h,l-c,h,"L",l-c,h,l-c,h-w,"L",l-c,h-w,E-c,h-w,"L",E-c,h-w,E-
c,h,"L",E-c,h,E,h];break;case 4:f=["M",l,h,l-c,h,"L",l-c,h,l-c,h-w,"L",l-c,h-w,n+c,h-w,"L",n+c,h-w,n+c,h,"L",n+c,h,n,h]}else switch(x){case 1:f=["M",u,h,u+(E-u)/2,h,"L",u+(E-u)/2,h,u+(E-u)/2,y,"L",u+(E-u)/2,y,E,y];f=u<=E?["M",u,h,u+(E-u)/2,h,"L",u+(E-u)/2,h,u+(E-u)/2,y,"L",u+(E-u)/2,y,E,y]:["M",u,h,u+c,h,"L",u+c,h,u+c,h+(y-h)/2,"L",u+c,h+(y-h)/2,E-c,h+(y-h)/2,"L",E-c,h+(y-h)/2,E-c,y,"L",E-c,y,E,y];break;case 2:x=0>n-u?0:n-u;f=["M",u,h,u+c+x,h,"L",u+c+x,h,u+c+x,y,"L",u+c+x,y,n,y];break;case 3:x=0>
l-E?0:l-E;f=["M",l,h,l-c-x,h,"L",l-c-x,h,l-c-x,y,"L",l-c-x,y,E,y];break;case 4:f=l>n?["M",l,h,l-(l-n)/2,h,"L",l-(l-n)/2,h,l-(l-n)/2,y,"L",l-(l-n)/2,y,n,y]:["M",l,h,l-c,h,"L",l-c,h,l-c,h+(y-h)/2,"L",l-c,h+(y-h)/2,n+c,h+(y-h)/2,"L",n+c,h+(y-h)/2,n+c,y,"L",n+c,y,n,y]}t.connector?t.connector.animate({path:f}):(l=ka.animation({"stroke-opacity":p.alpha},d,"normal"),t.connector=a.path(f,z).attr({stroke:p.color,"stroke-opacity":0,"stroke-width":p.thickness,"stroke-dasharray":p.dashedStyle}).animate(l.delay(d)));
l={fromTaskId:p.fromTaskId,toTaskId:p.toTaskId,fromTaskConnectStart:p.fromTaskConnectStart,toTaskConnectStart:p.toTaskConnectStart,link:p.link,sourceType:"connector"};t.tracker=a.path(f,z).attr({stroke:Oa,"stroke-width":ha(p.thickness,10),ishot:!0,cursor:p.link?"pointer":""}).data("dataObj",p).data("eventArgs",l).click(K);t.tracker.hover(U,G)}}},Ra["renderer.cartesian"])}]);
