/*
 FusionCharts JavaScript Library
 Copyright FusionCharts Technologies LLP
 License Information at <http://www.fusioncharts.com/license>

 @version 3.7.1
*/
FusionCharts.register("module",["private","modules.renderer.js-gradientlegend",function(){function V(b,d,l){var m=b[0],n=b[1];b=b[2];m+=(d[0]-m)*l;n+=(d[1]-n)*l;d=b+(d[2]-b)*l;return{hex:(ta+(m<<16|n<<8|d).toString(16)).slice(-6),rgb:[m,n,d]}}function X(b,d){return b.maxvalue-d.maxvalue}function E(b){var d,l,m=b.colorRange||{},n=b.dataMin,x=b.dataMax,t=b.sortLegend||!1,h=b.mapByCategory||!1,w=b.defaultColor,e=b.numberFormatter,c=m.color;b=this.colorArr=[];var g,f,a;this.mapByCategory=h;"1"===m.mapbypercent&&
(this.mapbypercent=!0);if("1"===m.gradient&&!h){this.gradient=!0;l=Da(ea(m.startcolor,m.mincolor,m.code));t=ja(Da(ea(l,w,"CCCCCC")));h=this.scaleMin=G(m.startvalue,m.minvalue,this.mapbypercent?0:n);b.push({code:l,maxvalue:h,label:Y(m.startlabel),codeRGB:ja(l)});if(c&&(d=c.length))for(n=0;n<d;n+=1)w=c[n],l=Da(ea(w.color,w.code)),f=G(w.value,w.maxvalue),a=G(w.minvalue),f>h&&b.push({code:l,maxvalue:f,userminvalue:a,label:Y(ea(w.label,w.displayvalue)),codeRGB:ja(l)});b.sort(X);d=b.length;for(n=1;n<d;n+=
1)w=b[n],l=w.maxvalue-h,0<l?(w.minvalue=h,w.range=l,h=w.maxvalue):(b.splice(n,1),--n,--d);2<=b.length&&(this.scaleMax=h,b[n-1].label=ea(m.endlabel,b[n-1].label,b[n-1].displayvalue));1===b.length&&(f=G(m.maxvalue,this.mapbypercent?100:x),b.push({minvalue:h,maxvalue:f,range:f-h,label:m.endlabel}),this.scaleMax=f,delete b[0].code);m=b[0];x=b[b.length-1];m.code&&x.code||(l=fa(t),d=Ga((l[2]=0,l)),l=Ga((l[2]=100,l)),m.code||(m.codeRGB=d,m.code=ua(d)),x.code||(x.codeRGB=l,x.code=ua(l)));d=b.length;for(n=
1;n<d;n+=1)if(w=b[n],w.code){if(g)for(x=w,a=m.maxvalue,c=x.maxvalue-a;g<n;g+=1)t=b[g],l=V(m.codeRGB,x.codeRGB,(t.maxvalue-a)/c),t.code=l.hex,t.codeRGB=l.rgb;g=null;m=w}else g=g||n;if(void 0===this.scaleMin||void 0===this.scaleMax)this.noValidRange=!0}else if(c&&(d=c.length)){for(n=0;n<d;n+=1)w=c[n],l=ea(w.color,w.code),f=G(w.maxvalue),a=G(w.minvalue),g=ea(w.label,w.displayvalue,h?Z:e.dataLabels(a)+" - "+e.dataLabels(f)),(l&&f>a||h&&g)&&b.push({code:l,maxvalue:f,minvalue:a,label:Y(g),labelId:g.toLowerCase()});
b.length?t&&b.sort(X):this.noValidRange=!0}}function aa(b,d){return d?H(100*b)/100+"%":Q(b,Z).toString()}var qa=this,b=qa.hcLib,va=qa.window,va=/msie/i.test(va.navigator.userAgent)&&!va.opera,G=b.pluckNumber,ta=b.COLOR_BLACK,d=b.COLOR_GLASS,Ea=b.FC_CONFIG_STRING,ya=b.graphics,Ga=ya.HSBtoRGB,fa=ya.RGBtoHSB,ua=ya.RGBtoHex,ja=ya.HEXtoRGB,ka=b.COMMASTRING,Z=b.BLANKSTRING,Y=b.parseUnsafeString,wa=b.graphics.convertColor,Aa=b.POSITION_TOP,oa=b.POSITION_MIDDLE,za=b.POSITION_START,Ha=b.POSITION_END,xa=b.graphics.getDarkColor,
ra=b.graphics.getLightColor,ea=b.pluck,Q=b.getValidValue,sa=b.toRaphaelColor,Ba=b.hasTouch,H=Math.round,R=Math.max,T=Math.min,Ia=Math.abs,ba,Ja,Ca,Ka="rgba(192,192,192,"+(va?.002:1E-6)+")",Da=function(b){return b&&b.replace(/^#?([a-f0-9]+)/ig,"$1")};E.prototype={getColorObj:function(b){var d=this.colorArr,l=this.gradient?1:0,m=d[l],n;if(this.mapByCategory){for(b=Y(b).toLowerCase();m;){if(m.labelId===b)return{code:m.code,seriesIndex:l};l+=1;m=d[l]}return{outOfRange:!0}}if(this.gradient){if(this.scaleMin<=
b&&this.scaleMax>=b){for(;m&&m.maxvalue<b;)l+=1,m=d[l];b=(b-m.minvalue)/m.range;return{code:V(d[l-1].codeRGB,m.codeRGB,b).hex}}return{outOfRange:!0}}for(;m;){if(m.maxvalue>b&&m.minvalue<=b)return{code:m.code,seriesIndex:l};m.maxvalue===b&&(n=l);l+=1;m=d[l]}return(m=d[n])&&m.maxvalue===b?{code:m.code,seriesIndex:n}:{outOfRange:!0}}};E.prototype.constructor=E;b.colorRange=E;ba=b.configureGradientLegendOptions=function(b,d){var l=b.legend,m=d.chart;l.legendSliderBorderWidth=G(m.legendpointerborderthickness,
1);l.legendSliderBorderColor=wa(ea(m.legendpointerbordercolor,ta),G(m.legendpointerborderalpha,100));l.legendSliderWidth=G(m.legendpointerwidth,m.legendpointerswidth,12);l.legendSliderHeight=G(m.legendpointerheight,m.legendpointersheight,12);l.legendColorBoxBorderColor=l.borderColor;l.legendColorBoxBorderWidth=l.borderWidth;l.legendScaleColor=wa(ea(m.legendscalelinecolor,ta),G(m.legendscalelinealpha,100));l.legendScalePadding=G(m.legendscalepadding,4);l.legendScaleLineThickness=G(m.legendscalelinethickness,
1);l.legendScaleTickDistance=G(m.legendscaletickdistance,6);l.itemStyle.cursor="default";l.interActivity=G(m.interactivelegend,1)};b.placeGLegendBlockRight=function(b,d,l,m,n){this.configureLegendOptions(b,d.chart,!0,n,l);ba(b,d);n=this.snapLiterals||(this.snapLiterals={});var x=b[Ea],t=this.smartLabel||x.smartLabel,h=b.legend,w=b.chart.spacingRight,e,c,g=h.textPadding=2,f=2*g,a=h.title.padding,z=0,ga=0,k=2*h.padding;d=G(d.chart.legendpadding,7)+h.borderWidth/2+1;var C=b.colorRange||{},v=C.colorArr,
la=C.mapbypercent,W=C.scaleMin,q=C.scaleMax-W,U=h.legendSliderWidth,N=h.legendSliderHeight/2;c=h.legendScalePadding;var r=h.legendScaleTickDistance,u=h.itemStyle||{};e=G(parseInt(u.lineHeight,10)||12);var y=.75*e,S=l-k,A,J,p=0,F,B,D,L,P,I,K;m-=k;if(!C.noValidRange&&v&&1<(J=v.length)){--J;h.title.text!==Z&&(t.setStyle(h.title.style),e=t.getSmartText(h.title.text,S,R(e,m/4)),h.title.text=e.text,z=e.width+k,m-=ga=e.height+a);t.setStyle(u);e=t.lineHeight;S-=r+c+U;h.colorBoxX=U;a=R(e,S/2);S=T(S-a-4,e);
F=R(e,m/2);A=m/4;r=v[0];r.scaleLabel=aa(r.maxvalue,la);e=t.getSmartText(r.label,A,S);r.label=e.text;u=e.height;r.labelY=y-e.height/2;c=t.getSmartText(r.scaleLabel,a,F);r.scaleLabel=c.text;C=c.height/2;B=c.width;r.scaleLabelY=y-c.height/2;h.colorBoxY=R(C,e.width+f,N)+ga;r=K=v[J];r.scaleLabel=aa(r.maxvalue,la);e=t.getSmartText(r.label,A,S);r.label=e.text;u=R(u,e.height);r.labelY=y-e.height/2;c=t.getSmartText(r.scaleLabel,a,F);r.scaleLabel=c.text;B=R(B,c.width);A=c.height/2;e=R(e.width+f,A,N);r.scaleLabelY=
y-c.height/2;h.colorBoxHeight=N=m-h.colorBoxY-e;F=N-A;D=N/q;P=T(N-p,F-C)-4;for(A=1;A<J;A+=1)r=v[A],L=(r.maxvalue-W)*D,e=t.getSmartText(r.label,2*T(L-p,N-L),S),r.label=e.text,u=R(u,e.height),r.labelY=y-e.height/2,e=e.width/2,r.scaleLabel=aa(r.maxvalue,la),c=t.getSmartText(r.scaleLabel,a,2*T(L-C,F-L)),r.scaleLabel=c.text,B=R(B,c.width),I=c.height/2,r.scaleLabelY=y-c.height/2,P=T(P,(L-R(I+C,e+p)-4)*q/r.range),p=e+L,C=I+L;P=R(T(P,(T(F-C,N-p)-4)*q/K.range,.3*m),0);h.colorBoxHeight-=P;h.colorBoxWidth=u&&
u+f||15;h.height=h.totalHeight=m+ga+k-P;h.width=(B&&B+g)+h.colorBoxWidth+U+h.legendScaleTickDistance+h.legendScalePadding+k;h.width<z&&(h.colorBoxX+=(z-h.width)/2,h.width=z);h.width>l&&(h.width=l);n.legendstartx=x.width-w-h.width;n.legendwidth=h.width;n.legendendx=n.legendstartx+n.legendwidth;n.legendheight=h.height;d+=h.width;b.chart.marginRight+=d;return d}h.enabled=!1;return 0};b.placeGLegendBlockBottom=function(b,d,l,m,n){this.configureLegendOptions(b,d.chart,!1,n,l);ba(b,d);n=this.snapLiterals||
(this.snapLiterals={});var x=b[Ea],t=this.smartLabel||x.smartLabel,h=b.legend,w=b.chart,e=w.spacingBottom,c=w.spacingLeft,w=w.spacingRight,g,f,a=h.textPadding=2,z=h.title.padding,ga=0,k=0,C=2*h.padding;d=G(d.chart.legendpadding,7)+h.borderWidth/2+1;var v=b.colorRange||{},la=v.colorArr,W=v.mapbypercent,q=v.scaleMin,U=v.scaleMax-q,N=h.legendSliderWidth,r=h.legendSliderHeight,u=h.legendScalePadding,y=h.legendScaleTickDistance,S=h.itemStyle||{};g=G(parseInt(S.lineHeight,10)||12);var A=.75*g,J=m-C,p,F,
B,D,L=0,P,I,K;l-=C;if(!v.noValidRange&&la&&1<(F=la.length)){--F;h.title.text!==Z&&(t.setStyle(h.title.style),g=t.getSmartText(h.title.text,l,J/3),h.title.text=g.text,ga=g.width+C,J-=k=g.height+z);t.setStyle(S);g=t.lineHeight;J-=y+u+r;z=R(g,J/2);S=T(J-z-4,g);p=l/4;D=2*p;B=la[0];B.scaleLabel=aa(B.maxvalue,W);g=t.getSmartText(B.label,p,S);B.label=g.text;J=g.height;B.labelY=A-g.height/2;f=t.getSmartText(B.scaleLabel,D,z);B.scaleLabel=f.text;u=f.width/2;y=f.height;B.code||(B.code=ea(h.minColor,"CCCCCC"));
h.colorBoxX=R(u,g.width+a,N);B=v=la[F];B.scaleLabel=aa(B.maxvalue,W);g=t.getSmartText(B.label,p,S);B.label=g.text;J=R(J,g.height);B.labelY=A-g.height/2;f=t.getSmartText(B.scaleLabel,D,z);B.scaleLabel=f.text;y=R(y,f.height);B=f.width/2;g=R(g.width+a,B,N);h.colorBoxWidth=N=l-h.colorBoxX-g;D=N-B;P=N/U;K=T(N-L,D-u)-4;for(p=1;p<F;p+=1)B=la[p],I=(B.maxvalue-q)*P,g=t.getSmartText(B.label,2*T(I-L,N-I),S),B.label=g.text,J=R(J,g.height),B.labelY=A-g.height/2,g=g.width/2,B.scaleLabel=aa(B.maxvalue,W),f=t.getSmartText(B.scaleLabel,
2*T(I-u,D-I),z),B.scaleLabel=f.text,y=R(y,f.height),f=f.width/2,K=T(K,(I-R(f+u,g+L)-4)*U/B.range),L=g+I,u=f+I;K=R(T(K,(T(D-u,N-L)-4)*U/v.range,.3*l),0);h.colorBoxWidth-=K;h.width=l+C-K;h.width<ga&&(h.colorBoxX+=(ga-h.width)/2,h.width=ga);h.colorBoxY=k+r;h.colorBoxHeight=J&&J+2*a||15;h.height=h.totalHeight=(y&&y+a)+h.colorBoxHeight+k+r+h.legendScaleTickDistance+h.legendScalePadding+C;h.height>m&&(h.height=m);n.legendstartx=c+.5*(x.width-c-w-h.width)+(h.x||0);n.legendwidth=h.width;n.legendendx=n.legendstartx+
n.legendwidth;n.legendstarty=x.height-e-h.height;n.legendheight=h.height;n.legendendy=n.legendstarty+n.legendheight;d+=h.height;b.chart.marginBottom+=d;return d}h.enabled=!1;return 0};Ja=function(){return{point:this}};Ca=function(b){return H(100*b)/100};b.rendererRoot.drawGradientLegendItem=function(b){var E=this,l=E.paper,m=E.options,n=E.canvasLeft,x=E.canvasTop,t=E.canvasWidth,h=E.canvasHeight,w=m.colorRange,e=m.chart.textDirection,c,g,f,a,z=m.legend,ga=G(z.padding,4),k=z.itemStyle,m=z.symbolStyle,
C=z.interActivity,v=b.elements;b=v.elementGroup.trackTooltip(!0);var la="vertical"===z.layout,W,q,U,N,r,u,y=0,S=z.lighting3d,A=z.colorBoxWidth,J=z.colorBoxHeight,p=A,F=J,B={FCcolor:{color:Z,alpha:Z,angle:0,ratio:Z}},D=B.FCcolor,L=z.colorBoxX+ga,P=z.colorBoxY+ga,I,K,Na=z.legendColorBoxBorderColor,Oa=z.legendColorBoxBorderWidth,Fa=["M"],ha=z.legendScaleColor;u=z.legendScalePadding;var ba=z.legendScaleLineThickness,V=ba%2/2;g=z.legendScaleTickDistance;var T=z.legendSliderWidth,aa=z.legendSliderHeight;
r=F/2;a=p/2;var Q=T/2,ca=aa/2,X,da,Y;K=0;var ia=ra("ABABAB",50),ga=xa("ABABAB",70),z=wa("ABABAB",100),ga=wa(ga,100),ia=wa(ia,100),ja,O={isFirst:!0},M={},pa,ma,na,fa;if(w&&(c=w.colorArr)&&1<(f=c.length)){O.toolText=pa=U=w.scaleMin;M.toolText=ma=w=w.scaleMax;N=w-U;O.snapPX=M.snapPX=0;O.tooltipConstraint=M.tooltipConstraint="chart";O.getLabelConfig=M.getLabelConfig=Ja;O.tooltipPos=[0,0];M.tooltipPos=[0,0];M.tooltipOffsetReference=O.tooltipOffsetReference={};M.tooltipOffsetReference.left=O.tooltipOffsetReference.left+=
n-20;M.tooltipOffsetReference.top=O.tooltipOffsetReference.top+=x;na=v.colorBox=l.group("colorBox",b);if(la){O.tooltipPos[0]=M.tooltipPos[0]=t+n;K=270;D.angle=90;n=L-T;t=L+p;x=P-ca;W=P+ca;n=H(L-T)+.5;t=H(L)+.5;x=H(P-ca)+.5;W=H(P+ca)+.5;X=H(L+p)+.5;Y=H(P-2)+.5;q=H(P+2)+.5;I=H(P)+.5;h=L-Q/2;da=H(h-ca)+.5;h=H(h)+.5;r=P-ca/2;ca=H(r+ca)+.5;r=H(r)+.5;A/=2;Q=["M",n,x,"L",t,x,t,Y,X,I,t,q,t,W,n,W,"Z","M",da,r,"L",h,r,"M",da,I,"L",h,I,"M",da,ca,"L",h,ca];ca=["M",n+1,x,"L",n+1,W,"M",da,r-1,"L",h,r-1,"M",da,
I-1,"L",h,I-1,"M",da,ca-1,"L",h,ca-1];r=L+p+u;W=H(r+g)+V;r=H(r)+V;I=L+a;da=f-1;for(g=0;g<f;g+=1)a=c[g],t=(a.maxvalue-U)/N,q=F*t+P,u=H(q)+V,g?(D.ratio+=ka,D.color+=ka,D.alpha+=ka,Fa.push("L",r,u,W,u,"M",r,u),g===da?(h=Ha,u=q+2):(h=oa,u=q)):(Fa.push(r,u,"L",W,u,"M",r,u),h=za,u=q-2),D.ratio+=100*(t-y),D.color+=ea(a.code,ta),D.alpha+=ea(a.alpha,100),y=t,a.legendItem=l.text(b).attr({text:a.label,x:I,y:u,"text-anchor":h,direction:e,"vertical-align":oa}).rotate(K,I,u).css(k),a.legendSymbol=l.text(b).attr({text:a.scaleLabel,
x:W,y:q,"text-anchor":za,direction:e,"vertical-align":oa}).css(k);O.xMin=M.xMin=0;O.xMax=M.xMax=0;O.yMin=M.yMin=0;O.yMax=M.yMax=F;O.x=M.x=0;O.y=0;M.y=F;e=aa+p;c=T}else{O.tooltipPos[1]=M.tooltipPos[1]=h+x;n=H(L-Q)+.5;t=H(L+Q)+.5;x=H(P-aa)+.5;W=H(P+F)+.5;X=H(L-2)+.5;h=H(L+2)+.5;da=H(L)+.5;Y=H(P)+.5;q=P-ca/2;I=H(q-ca)+.5;q=H(q)+.5;K=L-Q/2;a=H(K+Q)+.5;K=H(K)+.5;J/=2;Q=["M",n,x,"L",t,x,t,Y,h,Y,da,W,X,Y,n,Y,"Z","M",K,I,"L",K,q,"M",da,I,"L",da,q,"M",a,I,"L",a,q];ca=["M",n,x+1,"L",t,x+1,"M",K-1,I,"L",K-1,
q,"M",da-1,I,"L",da-1,q,"M",a-1,I,"L",a-1,q];u=P+F+u;K=H(u+g)+V;u=H(u)+V;q=P+r;da=f-1;for(g=0;g<f;g+=1)a=c[g],t=(a.maxvalue-U)/N,W=p*t+L,r=H(W)+V,g?(D.ratio+=ka,D.color+=ka,D.alpha+=ka,Fa.push("L",r,u,r,K,"M",r,u),g===da?(h=za,r=W+2):(h=oa,r=W)):(Fa.push(r,u,"L",r,K,"M",r,u),h=Ha,r=W-2),D.ratio+=100*(t-y),D.color+=ea(a.code,ta),D.alpha+=ea(a.alpha,100),y=t,a.legendItem=l.text(b).attr({text:a.label,x:r,y:q,"text-anchor":h,direction:e,"vertical-align":oa}).css(k),a.legendSymbol=l.text(b).attr({text:a.scaleLabel,
x:W,y:K,"text-anchor":oa,direction:e,"vertical-align":Aa}).css(k);O.xMin=M.xMin=0;O.xMax=M.xMax=p;O.yMin=M.yMin=0;O.yMax=M.yMax=0;O.y=M.y=0;O.x=0;M.x=p;e=T;c=aa+F}v.colorBox=l.rect(na).attr({x:L,y:P,width:p,height:F,fill:sa(B),stroke:Na,strokeWidth:Oa});S&&(v.colorBoxEffect=l.rect(na).attr({x:L,y:P,width:A,height:J,fill:d,"stroke-width":0}));v.scale=l.path(b).attr({path:Fa,stroke:ha,"stroke-width":ba});ja=function(a,e,c,b,g){var f;la?(f=e*N/F+U,b=0<e?b:b+e+.01):(f=a*N/p+U,c=0<a?c:c+a+.01);a=Ca(f);
g?(v.slider1.translate(c,b),v.slider1Effect.translate(c,b),v.slider1Tracker.toFront().translate(c,b).tooltip(a,null,null,!0),pa=f):(v.slider2.translate(c,b),v.slider2Effect.translate(c,b),v.slider2Tracker.toFront().translate(c,b).tooltip(a,null,null,!0),ma=f);C&&(fa=clearTimeout(fa),fa=setTimeout(function(){E.setScaleRange&&E.setScaleRange(pa,ma)},100))};f=function(a,e){var c=0,b=c,g,f=this.isFirst,d=f?M:O;if(la){b=this._startY+e;0>=b&&(b=0);b>F&&(b=F);if(f?b>d.y:b<d.y)b=d.y;Ia(b-this.y)>=(this.snapPX||
0)&&(g=!0)}else{c=this._startX+a;0>=c&&(c=0);c>p&&(c=p);if(f?c>d.x:c<d.x)c=d.x;Ia(c-this.x)>=(this.snapPX||0)&&(g=!0)}g&&(ja(c,b,c-this.x,b-this.y,f),this.x=c,this.y=b)};S=function(){var a=this.isFirst;this._startX=this.x;this._startY=this.y;this._scaleStart=pa;this._scaleEnd=ma;qa.raiseEvent("LegendPointerDragStart",{pointerIndex:a?0:1,pointers:[{value:pa},{value:ma}],legendPointerHeight:aa,legendPointerWidth:T},E.logic.chartInstance)};A=function(){var a=this._scaleStart,c=this._scaleEnd;qa.raiseEvent("LegendPointerDragStop",
{pointerIndex:this.isFirst?0:1,pointers:[{value:pa},{value:ma}],legendPointerHeight:aa,legendPointerWidth:T},E.logic.chartInstance);a===pa&&c===ma||qa.raiseEvent("LegendRangeUpdated",{previousMinValue:a,previousMaxValue:c,minValue:pa,maxValue:ma},E.logic.chartInstance);delete this._scaleStart;delete this._scaleEnd};J=Ca(U);v.slider1=l.path(b).attr({path:Q,fill:z,strokeWidth:1,stroke:ga});v.slider1Effect=l.path(b).attr({path:ca,fill:"none",strokeWidth:1,stroke:ia});Ba&&(n-=.5*(R(30,e)-e),x-=.5*(R(40,
c)-c),e=R(30,e),c=R(40,c));v.slider1Tracker=l.rect(b).attr({ishot:!0,width:e,height:c,x:n,y:x,fill:Ka,stroke:"none"}).drag(f,S,A,O,O,O).tooltip(J,null,null,!0).css(m);J=Ca(w);v.slider2=l.path(b).attr({path:Q,fill:z,strokeWidth:1,stroke:ga}).translate(M.x,M.y);v.slider2Effect=l.path(b).attr({path:ca,fill:"none",strokeWidth:1,stroke:ia}).translate(M.x,M.y);v.slider2Tracker=l.rect(b).attr({ishot:!0,width:e,height:c,x:n,y:x,fill:Ka,stroke:"none"}).translate(M.x,M.y).css(m).drag(f,S,A,M,M,M).tooltip(J,
null,null,!0)}}}]);
FusionCharts.register("module",["private","modules.renderer.js-maps",function(){var V=this,X=V.window,E=V.hcLib,aa=E.chartAPI,qa=X.document,b=E.pluck,va=E.imprint,G=E.extend2,ta=E.parseTooltext,d=E.pluckNumber,Ea=E.pluckFontSize,ya=E.HCstub,Ga=G(E.defaultPaletteOptions,{foregroundcolor:"333333",foregroundalpha:"100",foregrounddarkcolor:"111111",foregrounddarkalpha:"100",foregroundlightcolor:"666666",foregroundlightalpha:"100",backgroundlightcolor:"FFFFFF",backgroundlightalpha:"100",backgroundlightangle:90,
backgroundlightratio:"",backgroundcolor:"FFFFCC",backgroundalpha:"100",backgrounddarkcolor:"ffcc66",backgrounddarkalpha:"100",backgrounddarkangle:270,backgrounddarkratio:"",shadow:1}),fa=E.setLineHeight,ua=E.getValidValue,ja=E.parseUnsafeString,ka=E.getFirstColor,Z=E.graphics.convertColor,Y=E.hashify,wa=E.getDashStyle,Aa=X.navigator.userAgent,oa=/msie/i.test(Aa)&&!X.opera,za=/AppleWebKit/.test(Aa),Ha=/stroke/ig,xa=E.hasSVG,ra=E.FC_CONFIG_STRING,ea=X.Math,Q=ea.min,sa=ea.max,Ba=ea.ceil,Aa=!/fusioncharts\.com$/i.test(X.location.hostname),
H=E.toRaphaelColor,R={left:"start",right:"end",center:"middle"},T=function(e,c){var b;e||(e={});for(b in c)e[b]=c[b];return e},Ia=function(e){var c=this.parentNode;if(!c)return!1;for(;c&&c!==qa.documentElement;){if(c===e)return!0;c=c.parentNode}return!1},ba=function(e,c){var b=c?T(e.FCcolor,c):{FCcolor:e};b.toString=H;return b},Ja=function(e,c){var b,f;this.index=c;for(f in e)b=Ga[e[f]],this[f]=b instanceof Array?b[c]:b},Ca={right:function(e,c){return c},left:function(e,c){return e-c},center:function(e,
c){return 2*Q(c,e-c)}},Ka={top:function(e,c){return c},middle:function(e,c){return 2*Q(c,e-c)},bottom:function(e,c){return e-c}},Da=function(e,c,b,f){c=Q(e,c);e=.02*c;c*=.07;f=parseFloat(f);b=parseFloat(b);return isNaN(f)||isNaN(b)?isNaN(f)?isNaN(b)?{min:e,max:c}:{min:parseInt(b/10,10),max:b}:{min:f,max:10*f}:f<b?{min:f,max:b}:{min:b,max:f}},Ma=function(e){for(var c=e&&e.length||0,b={},f;c--;)f=e[c],void 0!==f.id&&(b[f.id.toLowerCase()]=f);return b},La=function(e,c){var b,f={};c=c||1;if(!e||"object"!==
typeof e)return f;for(b in e)Ha.test(b)||("stroke-width"===b?(f[b]=Number(e[b])/c,za&&(f[b]=f[b]&&Ba(f[b])||0)):f[b]=e[b]);return f},l=function(){this.hoverEntity&&(E.raiseEvent.apply(E,this.hoverEntityEventArgs),delete this.hoverEntityEventArgs,this.hoverEntity&&this.hoverEntityAttr&&this.hoverEntity.attr(this.hoverEntityAttr),delete this.hoverEntityAttr,this.hoverEntity=null)},m=function(e,c){var b=e&&e.length||!1,f=c||"id",a={},d;if(!e)return e;for(;b--;)d=e[b],void 0!==d[f]&&(a[d[f].toLowerCase()]=
d);return a},n=function(e,c,b,f){function a(){var a=this,c=a.entityPathMap,e=a.data,b=a.items,g,e=Ma(e);u=function(){for(var f,k=c[g];k;)b[g]?a=null:((f=e[g])?f.mapItem=b[g]=new x(g,va(d(f),k),q,a.group):b[g]=new x(g,k,q,a.group),g=k.nextId&&k.nextId.toLowerCase(),k=void 0!==g&&c[g]||null);C.call(a)};y=function(){var g,f,k=r,u,h=0;for(u in n)if(!b[u]&&(g=c[u],(f=e[u])?f.mapItem=b[u]=new x(u,va(d(f),g),q,a.group):b[u]=new x(u,g,q,a.group),h+=1,delete n[u],h===k))break;h<m?(m-=h,setTimeout(y,0)):C.call(a)};
(g=v&&v.toLowerCase())?u():y()}function d(a){delete a.outlines;delete a.label;delete a.shortlabel;delete a.labelposition;delete a.labelalignment;delete a.labelconnectors;return a}function h(){var a=this.items,c=[],e,b={id:"entityLabels",items:c};for(e in a)a[e].drawLabel(c);U.addGroup(b)}function k(){var a=this.items,c;for(c in a)a[c].destroy();delete this.entityPathMap;delete this.data;delete this.chartObj;delete this.items;delete this.group}function C(){N.entities.labelsOnTop&&h.call(this);this.ready=
!0;q.checkComplete()}if(b&&b.getEntityPaths()){var v=b.getFirstId(),m=b.entityCount,n=b.getEntityPaths(!0),q=c,U=c.mapAnnotations,N=q.options,r=xa?100:50,u,y,S;this.entityPathMap=n;this.data=e;this.chartObj=q;this.items={};this.ready=!1;this.group=f||c.mapGroup;this.isReady=function(){return this.ready};a.call(this);this.drawLabels=h;this.destroy=k;this.init=a;this.initComplete=C;q.__canvasMouseOutListenerAdded||(q.__canvasMouseOutListenerAdded=!0,S=c.paper.canvas,E.addEvent(S,"mouseout",function(a){a=
a.originalEvent.relatedTarget||a.originalEvent.toElement;!oa||xa?a&&a.ownerSVGElement&&a.ownerSVGElement===S||l.call(q):a===qa.documentElement||a===c.container||a===c.container.parentElement?l.call(q):Ia.call(a,S)||l.call(q)}))}},x=function(e,c,g,f){function a(a){var c=this.featureConfig;return c&&"undefined"!==typeof c[a]?Boolean(c[a]):!1}function z(){var e;if(a.apply(this,["_ds"])){e=c.labels&&c.labels[0];if(!e)return;e=(p.useSNameInTooltip?e.shortText:e.text)+(isNaN(B)?"":p.tooltipSepChar+D)}else e=
(p.useSNameInTooltip?c.shortLabel:c.label)+(isNaN(B)?"":p.tooltipSepChar+D);return e}function h(a,e,g){e?g&&"undefined"!==typeof c.displayvalue?a=c.displayvalue:(a=b(p.includeNameInLabels?p.useShortName?a.shortText:a.text:""),p.includeValueInLabels&&!isNaN(B)&&(a=void 0===a?D:a+L+D)):a=a.text;return a}function k(a){for(var c=a&&a.length||0,e;c--;)e=a[c],this.connectorElem[c]=J.path(e,this.group).attr({transform:na.transform,stroke:Z(R,T),"shape-rendering":"crisp","stroke-width":Q})}function C(){var a=
this.chart.paper,c=xa||!oa?"litepath":"path",e=this.eJSON.outlines,b=this.group,f,d,z;f=e&&e.length||0;if(this.hasFeature("_ds")){if(this.hasFeature("isDataEnabled"))if(M)for(;f--;)d=e[f].outline,this.svgElems[f]={},this.svgElems[f].graphic=a[c](d,b).attr(na).tooltip(I).shadow(ka,g.shadowLayer);else for(;f--;)d=e[f].outline,this.svgElems[f]={},this.svgElems[f].graphic=a[c](d,b).tooltip(I).attr(na);else if(M)for(;f--;)z=G(G({},na),La(e[f].style,ma)),d=e[f].outline,this.svgElems[f]={},this.svgElems[f].graphic=
a[c](d,b).attr(z).tooltip(I).shadow(ka,g.shadowLayer);else for(;f--;)z=G(G({},na),La(e[f].style,ma)),d=e[f].outline,this.svgElems[f]={},this.svgElems[f].graphic=a[c](d,b).tooltip(I).attr(z);this.hasFeature("isDataEnabled")&&this.addMouseGestures()}else{if(M)for(;f--;)d=e[f],this.svgElems[f]={},this.svgElems[f].graphic=a[c](d,b).attr(na).tooltip(I).shadow(ka,g.shadowLayer);else for(;f--;)d=e[f],this.svgElems[f]={},this.svgElems[f].graphic=a[c](d,b).tooltip(I).attr(na);this.addMouseGestures()}return this}
function v(a){var e=this.chart;e.hoverEntityEventArgs=["entityrollout",this.eventArgs,e.fusionCharts,[e.fusionCharts.id,"rollOut",this.legacyEventArgs],a];fa&&this.isVisible&&(e.hoverEntity=this,e.hoverEntityAttr=this.revertAttr,this.attr(this.hoverAttr));E.raiseEvent("entityrollover",this.eventArgs,e.fusionCharts,[e.fusionCharts.id,"rollOver",this.legacyEventArgs],a)}function m(a,e,c){var b=this,f=b.chart,d=a.labelPosition,z=a.labelAlignment,u=b.svgElems[0]&&b.svgElems[0].graphic,k=a.style,p,y,A,
q,r;d?(u=d[0],d=d[1]):(d=u.getBBox(),u=d.x+d.width/2,d=d.y+d.height/2);z?(p=z[0],z=z[1],"right"===p?u-=X:"left"===p&&(u+=X),"top"===z?d-=X:"bottom"===z&&(d+=X)):(p="center",z="middle");y=ca;A=parseFloat(aa)/g.sFactor;q=Y;r=qa;!e&&k&&(k.color&&(y=k.color),k["font-size"]&&(A=parseFloat(k["font-size"])/g.sFactor),k["font-family"]&&(q=k["font-family"]),void 0!==k["font-weight"]&&(r="bold"===k["font-weight"]));return{x:u.toString(),y:d.toString(),wrapwidth:Ca[p](ua,u+wa)-X,wrapheight:Ka[z](va,d+ya)-X,
wrap:1,type:"text",align:p,valign:z,text:h(a,e,c),tooltext:I,link:O,bgcolor:"",bordercolor:"",fillcolor:y,fontsize:A,font:q,bold:r,onclick:function(a){V.raiseEvent("entityclick",b.eventArgs,g.fusionCharts,a)},onmouseover:function(a){b!==f.hoverEntity&&(l.call(b.chart),v.call(b,a))},ontouchstart:function(a){b!==f.hoverEntity&&(l.call(b.chart),v.call(b,a))}}}function n(a){var e=this.eJSON,c=this.hasFeature("isDataEnabled"),b,f;if(!H)return null;if(this.hasFeature("_ds"))for(f=(e=e.labels)&&e.length||
0;f--;)b=e[f],a.push(this.getLabelObject(b,c,!f)),b.labelConnectors&&this.drawLabelConnectors(b.labelConnectors);else b={text:e.label,shortText:e.shortLabel,labelAlignment:e.labelAlignment,labelPosition:e.labelPosition},a.push(this.getLabelObject(b,!0,!0)),e.labelConnectors&&this.drawLabelConnectors(e.labelConnectors)}function q(a,e){var c=this.svgElems,b;for(b in c)c[b].graphic&&c[b].graphic.attr(a,e)}function U(){var a=this.svgElems,e;this.isVisible=!0;for(e in a)a[e].graphic&&a[e].graphic.attr(na)}
function N(){var a=this.svgElems,e=this.chart,c;this.isVisible=!1;e.hoverEntity===this&&l.call(e);for(c in a)a[c].graphic&&a[c].graphic.attr(pa)}function r(a){V.raiseEvent("entityclick",this.node.__entity.eventArgs,g.fusionCharts,a);void 0!==O&&g.logic.linkClickFN.call({link:O})}function u(a){var e=this.node.__entity,c=e.chart;e!==c.hoverEntity&&(l.call(c),v.call(e,a))}function y(){var a=this.eJSON,e=this.svgElems,c;this.eventArgs={value:this.value,label:a.label,shortLabel:a.shortLabel,originalId:this.originalId||
this.id,id:this.id};this.legacyEventArgs={value:this.value,lName:a.label,sName:a.shortLabel,id:this.originalId||this.id};fa&&(this.hoverAttr={fill:this.hoverColor.toString()},this.revertAttr={fill:this.fillColor.toString()},ia!==ha&&(this.hoverAttr["stroke-width"]=ia,this.revertAttr["stroke-width"]=ha));if(!isNaN(B)||da)for(c in e)void 0!==O&&e[c].graphic.css({cursor:"pointer",_cursor:"hand"}),e[c].graphic.node.__entity=this,e[c].graphic.click(r).hover(u)}function S(){var a=this.svgElems,e=this.connectorElem,
c;for(c in a)a[c].remove&&a[c].remove();for(c in e)e[c].destroy&&e[c].destroy();delete this.value;delete this.formattedValue;delete this.toolText;delete this.fillColor;delete this.hoverColor;delete this.chart;delete this.group;delete this.id;delete this.isVisible;delete this.svgElems;delete this.connectorElem;delete this.renderer;delete this.options}if(c&&g&&void 0!==e){this.chart=g;this.eJSON=c;this.group=f;this.id=e;this.originalId=c.origId;this.isVisible=!0;this.svgElems={};this.connectorElem=
{};this.featureConfig=c.options;"object"===typeof this.featureConfig&&(this.featureConfig._ds=!0);var A=g.options,J=g.paper,p=A.entities,F=p.dataLabels.style;e=c.cleanValue;var B=null===e?void 0:e,D=this.formattedValue=c.formattedValue||"",L=p.labelSepChar,t=d(c.showtooltip,p.showTooltip);e=z.call(this);f={formattedValue:D,sName:c.shortLabel,lName:c.label};var I=t?ja(b(ta(b(c.tooltext,p.tooltext,e),[1,2,7,38,39],f,c))):"",K,w,x,H=d(c.showlabel,p.showLabels);f=b(c.bordercolor,p.borderColor);e=b(c.borderalpha,
p.borderAlpha);var t=1===p.scaleBorder,ha=d(c.borderthickness,p.borderThickness),R=b(c.labelconnectorcolor,p.connectorColor),T=b(c.labelconnectoralpha,p.connectorAlpha),Q=d(c.labelconnectorthickness,p.connectorThickness),Y=b(c.font,F.fontFamily),aa=d(parseInt(c.fontsize,10),parseInt(F.fontSize,10)),ca=b(c.fontcolor,F.color),X=d(c.labelpadding,p.labelPadding),da=p.hoverOnNull,fa=d(c.showhovereffect,c.usehovercolor,da?p.showHoverEffect:isNaN(B)?0:p.showHoverEffect),ia=d(c.borderhoverthickness,c.hoverborderthickness,
p.hoverBorderThickness),qa=d(c.fontbold,0),O=c.link,M=p.shadow;x=!oa||xa;F=g.sFactor/p.baseScaleFactor;K=g.strokeWidth;w=(x?p.baseScaleFactor:1)*K;var pa=p.hiddenEntityFillObject||(p.hiddenEntityFillObject={fill:ba({color:p.hiddenEntityColor,alpha:p.hiddenEntityAlpha}).toString()}),ma,na,ka,A=A[ra],ua=A._labelBaseWidth,va=A._labelBaseHeight,wa=A._labelXOffset,ya=A._labelYOffset;x?(ha=t?ha*w:ha/F,Q/=F,ma=t?F:g.sFactor,za&&(ha=ha&&Ba(ha)||0,Q=Q&&Ba(Q)||0)):(ha=t?ha*K:ha,ma=t?g.scaleFactor:p.baseScaleFactor);
p.showHiddenEntityBorder||(pa["stroke-width"]=0);void 0===ia?ia=ha:x?(ia=t?ha*w:ia/F,za&&(ia=ia&&Ba(ia)||0)):ia=t?ia*K:ia;!p.showNullEntityBorder&&isNaN(B)&&(ha=0);void 0!==b(c.color,c.alpha,c.angle,c.ratio)?(t=b(c.color,p.fillColor),A=b(c.alpha,p.fillAlpha),K=b(c.angle,p.fillAngle),w=b(c.ratio,p.fillRatio),x=ba({color:t,alpha:A,angle:K,ratio:w})):(p.fillColorObject||(p.fillColorObject=ba({color:b(p.fillColor),alpha:b(p.fillAlpha),angle:b(p.fillAngle),ratio:b(p.fillRatio)})),p.emptyColorObject||(p.emptyColorObject=
ba({color:b(p.nullEntityColor),alpha:b(p.nullEntityAlpha),angle:b(p.nullEntityAngle),ratio:b(p.nullEntityRatio)})),x=isNaN(B)?p.emptyColorObject:p.fillColorObject,t=x.FCcolor.color,A=x.FCcolor.alpha,K=x.FCcolor.angle,w=x.FCcolor.ratio);""===I&&(t=0);na={transform:xa||!oa?"":g.transformStr,stroke:Z(f,e),"stroke-width":ha,fill:(this.fillColor=x).toString()};f=A.split(",");ha&&f.push(e);ka={scalefactor:[F,g.sFactor],opacity:sa.apply(ea,f)/100};fa&&(void 0!==b(c.fillhovercolor,c.fillhoveralpha,c.fillhoverangle,
c.fillhoverratio,c.hoverfillcolor,c.hoverfillalpha,c.hoverfillratio,c.hoverfillangle)?(t=b(c.fillhovercolor,c.hoverfillcolor,p.hoverFillColor),A=b(c.fillhoveralpha,c.hoverfillalpha,p.hoverFillAlpha),K=b(c.fillhoverangle,c.hoverfillangle,p.hoverFillAngle),w=b(c.fillhoverratio,c.hoverfillratio,p.hoverFillRatio),e=ba({color:t,alpha:A,angle:K,ratio:w})):(p.hoverColorObject||(p.hoverColorObject=ba({color:p.hoverFillColor,alpha:p.hoverFillAlpha,angle:p.hoverFillAngle,ratio:p.hoverFillRatio})),e=p.hoverColorObject),
this.hoverColor=e);this.value=B;this.addMouseGestures=y;this.attr=q;this.draw=C;this.drawLabel=n;this.getLabelObject=m;this.destroy=S;this.show=U;this.hide=N;this.hasFeature=a;this.drawLabelConnectors=k;C.call(this);p.hideNullEntities&&void 0===B&&this.hide()}},t=function(e,c,b,f){this.id=e;this.definition=c;this.application=b;this.rapi=f;this.markerLabel=this.markerShape=this.label=this.options=this.value=this.hasValue=null;this.drawOptions={shape:null,label:null};this.drawComplete=!1;if(e=f.options)this._conf=
e[ra];this.init()},h=function(e,c,b,f){this.options=e;this.from=c;this.to=b;this.api=f;if(e=f.options)this._conf=e[ra]},w=function(e,c){function g(){var e=v.definition,b=m(e)||{},f=m(v.application)||{},g=v.shapes,k,p;if(e&&e.length){if(g&&g.length)for(e=g.length;e;--e)if(k=g[e-1],p=k.id.toLowerCase())a[p]=k;for(p in b){k=b[p];g=new t(p,k,f[p],c);if(e=g.getShapeId())g.shapeObj=a[e];d[p]=g}}}function f(){var e=v.items,b=v.shapes,f,g,k,p;if(e&&e.length){if(b&&b.length)for(f=b.length;f;--f)if(g=b[f-1],
p=g.id.toLowerCase())a[p]=g;for(f=e.length;f--;)if(g=e[f],p=g.id&&g.id.toLowerCase())void 0!==g.value&&""!==g.value&&parseFloat(g.value),g.mapItem=b=new t(p,g,null,c),k=b.getShapeId(),g.__hideMarker&&(b._isHidden=!0),k&&(b.shapeObj=a[k]),d[p]=b}}var a={},d={},ga=[],k=c.options.markers,C=c.options.connectors,v=e,l=c.mapAnnotations,n,q,U,N,r=[];this.items=d;(function(){var a=t.prototype,e=h.prototype,f;f=Boolean(b(k.hoverFillColor,k.hoverFillAlpha,k.hoverFillAngle,k.hoverFillRatio,k.hoverBorderThickness,
k.hoverBorderColor,k.hoverBorderAlpha));a.markerFont=k.dataLabels.style.fontFamily;a.markerFontSize=k.dataLabels.style.fontSize;a.markerFontColor=k.dataLabels.style.fontColor;a.showMarkerTooltip=k.showTooltip;a.showHoverEffect=f;a.tooltext=k.tooltext;a.showMarkerLabels=k.showLabels;a.markerLabelPadding=k.labelPadding;a.labelWrapWidth=k.labelWrapWidth;a.labelWrapHeight=k.labelWrapHeight;a.labelSepChar=k.labelSepChar;a.tooltipSepChar=k.tooltipSepChar;a.fillColor=k.fillColor;a.fillAlpha=k.fillAlpha;
a.fillRatio=k.fillRatio;a.fillAngle=k.fillAngle;a.hoverFillColor=k.hoverFillColor;a.hoverFillAlpha=k.hoverFillAlpha;a.hoverFillRatio=k.hoverFillRatio;a.hoverFillAngle=k.hoverFillAngle;a.startAngle=k.startAngle;a.shapeId=k.shapeId;a.borderThickness=k.borderThickness;a.borderColor=k.borderColor;a.borderAlpha=k.borderAlpha;a.hoverBorderThickness=k.hoverBorderThickness;a.hoverBorderColor=k.hoverBorderColor;a.hoverBorderAlpha=k.hoverBorderAlpha;a.markerRadius=k.radius;a.autoScale=k.autoScale?c.sFactor:
1;a.shadow=k.shadow;a.applyAll=k.applyAll;a.dataEnabled=k.dataEnabled;a.valueToRadius=k.valueToRadius;a=Boolean(b(C.hoverthickness,C.hovercolor,C.hoveralpha));e.showHoverEffect=a;e.showTooltip=C.showTooltip;e.tooltext=C.tooltext;e.thickness=C.thickness;e.color=C.color;e.alpha=C.alpha;e.hoverThickness=C.hoverthickness;e.hoverColor=C.hovercolor;e.hoverAlpha=C.hoveralpha;e.dashed=C.dashed;e.dashlen=C.dashLen;e.dashgap=C.dashGap;e.font=C.font;e.fontsize=C.fontSize;e.fontcolor=C.fontColor;e.bgcolor=C.labelBgColor;
e.bordercolor=C.labelBorderColor;e.shadow=C.shadow;e.hideOpen=C.hideOpen})();k.dataEnabled?f():g();(function(){var e=d,c=[],b,f,g,k;n=l.addGroup({fillalpha:"100",items:c});q=l.addGroup({items:[]});for(k in e)b=null,f=e[k],g=f.getShapeId(),f&&!f._isHidden&&(g&&(f.shapeObj=a[g]),b=f.draw()),b&&(f._annotationIndex=c.length,f.markerShape=b.markerShape&&n.addItem(b.markerShape),f.markerLabel=b.markerLabel&&q.addItem(b.markerLabel))})();(function(){var a=C.showLabels,e=v.connectors,b=e&&e.length,f=[],g=
[],k,q,l;if(b)for(r.push({id:"connectorLabels",fillalpha:"100",items:g}),r.push({id:"connectors",fillalpha:"100",items:f});b--;)if(l=e[b],l.from&&l.to&&(k=d[l.from.toLowerCase()],q=d[l.to.toLowerCase()],k&&q&&(!C.hideOpen||!k._isHidden&&!q._isHidden)&&(ga.push(q=new h(l,k,q,c)),q.connectJSON=k=q.computeConnectorJSON())))f.push(k),k.label&&a&&g.push(q.getLabelJSON())})();N=r.length;for(c.internalAnnotations={};N--;)U=r.shift(),U.id?c.internalAnnotations[U.id]=l.addGroup(U):l.addGroup(U);this.addMarkerItem=
function(e){var b,f;if((b=e.id.toLowerCase())&&!d[b]){delete e.value;e=new t(b,e,null,c);if(f=e.getShapeId())e.shapeObj=a[f];d[b]=e;b=e.draw();n&&q&&(e.markerShape=b.markerShape&&n.addItem(b.markerShape,!0),e.markerLabel=b.markerLabel&&q.addItem(b.markerLabel,!0))}}};h.prototype={constructor:h,computeConnectorJSON:function(){var e=this.api,c=this.options,g=this.from,f=this.to,a=c.link,z=c.label,h=d(c.showtooltip,this.showTooltip),k=h?b(c.tooltext,this.tooltext):"",C=b(c.thickness,this.thickness),
v=b(c.color,this.color),m=b(c.alpha,this.alpha),n=d(c.showhovereffect,this.showHoverEffect),q=b(c.hovercolor,this.hoverColor,v),t=b(c.hoveralpha,this.hoverAlpha,m),N=b(c.hoverthickness,this.hoverThickness,C),r=b(c.dashed,this.dashed),u=d(c.dashlen,this.dashlen),y=d(c.dashgap,this.dashgap),w;k&&(this.tooltext=k=ja(ta(k,[3,40,41,42,43],{label:z,fromId:g.definition.id,toId:f.definition.id,fromLabel:g.definition.label,toLabel:f.definition.label},c)));return g&&f?(w={fromMarkerId:g.id,toMarkerId:f.id,
label:z},G({type:"line"},{x:g.definition.x,y:g.definition.y,tox:f.definition.x,toy:f.definition.y,dashed:r,dashlen:u,dashgap:y,link:a,tooltext:h?k:"",thickness:C,color:v,alpha:m,label:z,showshadow:this.shadow,_hovereffect:n,_defaultattrs:{stroke:ba({color:v,alpha:m}).toString(),"stroke-width":C},_hoverattrs:{stroke:ba({color:q,alpha:t}).toString(),"stroke-width":N},onmouseover:function(a){var c=a.data,b=c.wrapper;b&&c.options._hovereffect&&(l.call(e),b.attr(c.options._hoverattrs));V.raiseEvent("connectorrollover",
w,e.fusionCharts,a)},onmouseout:function(a){var c=a.data,b=c.wrapper;b&&c.options._hovereffect&&b.attr(c.options._defaultattrs);V.raiseEvent("connectorrollout",w,e.fusionCharts,a)},onclick:function(a){V.raiseEvent("connectorClick",w,e.fusionCharts,a)}})):null},getLabelJSON:function(){var e=this.connectJSON;return G({type:"text"},{x:((Number(e.x)+Number(e.tox))/2).toString(),y:((Number(e.y)+Number(e.toy))/2).toString(),text:e.label,align:"center",valign:"middle",font:this.font,fontsize:this.fontsize/
this.api.sFactor,fillcolor:this.fontcolor,bgcolor:this.bgcolor,bordercolor:this.bordercolor,tooltext:this.tooltext})}};t.prototype={constructor:t,init:function(){var e;e=this.options=G({},this.definition);this.dataEnabled?isNaN(e.value)||""===e.value||(this.value=parseFloat(e.value),this.hasValue=!0):this.applyAll?this.options=G(e,this.application):this.application&&(this.options=G(e,this.application))},getShapeId:function(){return this.options.shapeid&&this.options.shapeid.toLowerCase()||this.shapeId},
getLabelOptions:function(e,c,b,f,a){var d,h=e&&e.toLowerCase();this.getLabelAlignment[h]||(h="center");e=Number(b.x);d=Number(b.y);b=void 0===f||void 0===a?b.radius||0:/^(top|bottom)$/ig.test(h)&&.5*a||/^(left|right)$/ig.test(h)&&.5*f||0;b=Number(b)+Number(c);return this.getLabelAlignment[h](e,d,b)},draw:function(){if(this.options){var e=this.rapi,c=this._conf,g=e.translateX,f=e.translateY,a=this.options,z=this.getShapeId(),h=a.scale||1,k=a.label||"",C=(a.labelpos||"top").toLowerCase(),v=void 0===
a.formattedValue?void 0:a.formattedValue,m=a.tooltext||this.tooltext,n=d(a.radius,this.markerRadius)*h*this.autoScale||1E-4,q=b(a.fillcolor,a.color,this.fillColor),t=b(a.fillalpha,a.alpha,this.fillAlpha),N=b(a.fillratio,this.fillRatio),r=b(a.fillangle,this.fillAngle),u=d(a.borderthickness,this.borderThickness),y=b(a.bordercolor,this.borderColor),w=b(a.borderalpha,this.borderAlpha),A=a.labelpadding||this.markerLabelPadding;if(z){m=m?ja(ta(m,[1,2,3],{formattedValue:v,label:k},a)):v?k+this.tooltipSepChar+
v:k;void 0!==v&&null!==v?k=k+this.labelSepChar+v:isNaN(h)?h=1:0>h?h=0:5<h&&(h=5);a={x:a.x.toString(),y:a.y.toString(),fillcolor:q,fillalpha:t,fillratio:N,fillangle:r,borderthickness:u,bordercolor:y,borderalpha:w,hovereffect:b(a.showhovereffect,this.showHoverEffect),radius:n.toString(),tooltext:this.showMarkerTooltip?m:"",link:a.link,showshadow:d(a.showshadow,this.shadow),_markerLabel:k,_markerId:a.id,id:(a.id+"").toLowerCase(),onmouseover:function(a){var c=a.data,b=c.options,d=c.bounds,k=b._markerEventArgs;
(c=c.wrapper)&&b.hovereffect&&(l.call(e),c.attr(b._hoverattrs));k||(k=b._markerEventArgs={x:d.x1/d.xs,y:d.y1/d.ys,scaledX:d.x1,scaledY:d.y1,chartX:g+d.x1,chartY:f+d.y1,id:b._markerId,label:b._markerLabel});V.raiseEvent("markerRollOver",k,e.fusionCharts,a)},onmouseout:function(a){var b=a.data,c=b.wrapper;c&&b.options.hovereffect&&c.attr(b.options._defaultattrs);V.raiseEvent("markerRollOut",b.options._markerEventArgs,e.fusionCharts,a)},onclick:function(a){V.raiseEvent("markerClick",a.data.options._markerEventArgs,
e.fusionCharts,a)}};"triangle"===z?G(a,{type:"polygon",sides:3,startangle:this.startAngle}):"diamond"===z?G(a,{type:"polygon",sides:4,startangle:this.startAngle}):"arc"===z?G(a,{type:"arc",startangle:0,endangle:360,innerradius:.6*n}):"circle"===z?a.type="circle":(A=this.getShapeArgs(),this.dataEnabled&&this.valueToRadius&&void 0!==a.radius?delete A.radius:(!A.radius&&(A.radius=this.markerRadius),A.radius=A.radius*h*this.autoScale),G(a,A));G(a,{hoverfillcolor:b(a.fillhovercolor,this.hoverFillColor,
a.fillcolor),hoverfillalpha:b(a.fillhoveralpha,this.hoverFillAlpha,a.fillalpha),hoverfillratio:b(a.fillhoverratio,this.hoverFillRatio,a.fillratio),hoverfillangle:b(a.fillhoverangle,this.hoverFillAngle,a.fillangle),hoverborderthickness:d(a.borderhoverthickness,this.hoverBorderThickness,a.borderthickness),hoverbordercolor:b(a.borderhovercolor,this.hoverBorderColor,a.bordercolor),hoverborderalpha:b(a.borderhoveralpha,this.hoverBorderAlpha,a.borderalpha)});a._defaultattrs={fill:ba({alpha:a.fillalpha,
color:a.fillcolor,angle:a.fillangle,ratio:a.fillratio}).toString(),"stroke-width":"0"!==a.showborder?a.borderthickness:0,stroke:Z(a.bordercolor,a.borderalpha)};a._hoverattrs={fill:ba({alpha:a.hoverfillalpha,color:a.hoverfillcolor,angle:a.hoverfillangle,ratio:a.hoverfillratio}).toString(),"stroke-width":"0"!==a.showborder?a.hoverborderthickness:0,stroke:Z(a.hoverbordercolor,a.hoverborderalpha)};"image"===a.type&&(a.borderthickness=a.borderthickness||0,a.onload=function(a){var b=this.options,c=a.width;
a=a.height;var f=(Number(b.x)-c/(2*e.sFactor))*e.sFactor,b=(Number(b.y)-a/(2*e.sFactor))*e.sFactor,g;if(c&&a)for(g in{wrapper:1,tracker:1})this[g]&&this[g].attr({x:f,y:b,width:c,height:a})});this.drawOptions.shape=a;if(!this.showMarkerLabels)return{markerShape:a};A=a.labelpadding||this.markerLabelPadding;h=this.getLabelOptions(C,A,a);C=h.align;z=h.valign;m=c._labelBaseWidth;v=c._labelBaseHeight;n=c._labelXOffset;c=c._labelYOffset;m=this.labelWrapWidth?this.labelWrapWidth:this.getWrapWidth[C](m,Number(h.x)+
n);c=this.labelWrapHeight?this.labelWrapHeight:this.getWrapHeight[z](v,Number(h.y)+c);m>A&&(m-=A);c>A&&(c-=A);this.drawOptions.label=G({type:"text"},{text:k,tooltext:a.tooltext,x:h.x,y:h.y,align:C,valign:h.valign,wrap:1,wrapwidth:m,wrapheight:c,fontsize:this.markerFontSize/e.sFactor,font:this.markerFont,fillcolor:this.markerFontColor});return{markerShape:a,markerLabel:this.drawOptions.label}}}},show:function(){this.setMarkerVisibility(!0)},hide:function(){this.setMarkerVisibility(!1)},setMarkerVisibility:function(e){var b=
this.rapi&&this.rapi.internalAnnotations;if(b=(b=b&&b.markers)&&b.items)if(b=b[this._annotationIndex])this._origFill||(this._origFill=ba({alpha:b.fillAlpha,color:b.fillColor,angle:b.fillAngle,ratio:b.fillRatio}),this._hideFill=ba({alpha:"0",color:b.fillColor,angle:b.fillAngle,ratio:b.fillRatio})),e?b.wrapper.attr({fill:this._origFill}):b.wrapper.attr({fill:this._hideFill})},getShapeArgs:function(){var e=G({},this.shapeObj),b;return e?("polygon"===e.type?3>e.sides?e.type="circle":e.startangle=this.startAngle:
"arc"===e.type&&(b=(e.radius||this.markerRadius)*this.autoScale,e.radius=b,e.innerradius=e.innerradius&&e.innerradius*this.autoScale||.6*b),e):null},destroy:function(){var e=this.markerShape,b=this.markerLabel,g;e&&e.destroy();b&&b.destroy();for(g in this)delete this[g]},getLabelAlignment:{top:function(e,b,g){return{x:e.toString(),y:(b-g).toString(),align:"center",valign:"top"}},left:function(e,b,g){return{x:(e-g).toString(),y:b.toString(),align:"right",valign:"middle"}},right:function(e,b,g){return{x:(e+
g).toString(),y:b.toString(),align:"left",valign:"middle"}},bottom:function(e,b,g){return{x:e.toString(),y:(b+g).toString(),align:"center",valign:"bottom"}},center:function(e,b){return{x:e.toString(),y:b.toString(),align:"center",valign:"middle"}}},getWrapWidth:{right:function(e,b){return b},left:function(e,b){return e-b},center:function(e,b){return 2*Q(b,e-b)}},getWrapHeight:{top:function(e,b){return b},middle:function(e,b){return 2*Q(b,e-b)},bottom:function(b,c){return b-c}}};T(E.eventList,{entityrollover:"FC_Event",
entityrollout:"FC_Event"});aa("geo",{name:"geo",friendlyName:"Map",revision:1,creditLabel:Aa,standaloneInit:!1,annotationInteractionEvents:!1,charttopmargin:10,chartrightmargin:10,chartbottommargin:10,chartleftmargin:10,baseWidth:400,baseHeight:300,baseScaleFactor:1,defaultSeriesType:"geo",rendererId:"maps",entities:{},draw:function(b,c){var g=this.renderer,f=this.chartInstance;g||(g=this.renderer=new aa("renderer."+this.rendererId));this.updateDefaultAnnotations();f.addEventListener("internal.mapdrawingcomplete",
function(a,b){c&&c.apply(this,[b.renderer]);a.detachHandler()});return g.init(this,b,function(a){a.checkComplete()})},chart:function(e,c){G(this.dataObj.chart,{charttopmargin:this.dataObj.chart.maptopmargin,chartrightmargin:this.dataObj.chart.maprightmargin,chartbottommargin:this.dataObj.chart.mapbottommargin,chartleftmargin:this.dataObj.chart.mapleftmargin,animation:this.dataObj.chart.animation||"0"});var g=this.dataObj,f=ya(g,e,c,this),a=g.chart,z=g.markers,h=f.chart,k=f[ra],l=h.useRoundEdges=1===
d(a.useroundedges),v=l?1:0,l=l?0:1,m=h.use3DLighting=1===d(a.use3dlighting,1),n=G({},f.tooltip.style),q=new Ja(this.colorPaletteMap,(0<a.palette&&6>a.palette?a.palette:d(this.paletteIndex,1))-1),t=b(a.basefont,"Verdana,sans"),w=Ea(a.basefontsize,10),r=b(a.basefontcolor,q.basefontcolor),u=Ea(a.outcnvbasefontsize,w),y=b(a.outcnvbasefont,t),x=u+"px",A=Y(b(a.outcnvbasefontcolor,r)),J=b(a.bgcolor,a.canvasbgcolor,q.canvasbgcolor),p=b(a.bgalpha,a.canvasbgalpha,q.canvasbgalpha),F=d(a.usevaluesformarkers,
g.markers&&g.markers.items&&g.markers.items.length,!(g.markers&&g.markers.application&&g.markers.application.length&&g.markers.definition&&g.markers.definition.length)),B,D,L,P,I,K,H,w=w+"px",r=Y(r);this.realtimeEnabled&&this.postHCJSONCreation&&this.postHCJSONCreation.call(this,f);h.events.click=this.linkClickFN;k.numberFormatter=this.numberFormatter;G(k,{width:e,height:c,showTooltip:d(a.showtooltip,this.showtooltip,1),showHoverEffect:d(a.showhovereffect,1),tooltipSepChar:b(a.tooltipsepchar,", "),
showValues:d(a.showvalues,this.showValues,1),showCanvasBG:b(a.showcanvasbg,1),useValuesForMarkers:F,adjustViewPortForMarkers:d(a.adjustviewportformarkers,F),flatScrollBars:d(a.flatscrollbars,0),scrollBar3DLighting:d(a.scrollbar3dlighting,1),outCanvasStyle:{fontFamily:y,color:A,fontSize:x},inCanvasStyle:{fontFamily:t,fontSize:w,color:r}});fa(k.outCanvasStyle);B=fa(k.inCanvasStyle);k.trendStyle=k.outCanvasStyle;"0"==k.showCanvasBG&&(p="0");D=b(a.entitybordercolor,a.bordercolor,q.plotbordercolor);L=
b(a.entityfillcolor,a.fillcolor,q.plotfillcolor);P=b(a.entityfillalpha,a.fillalpha,q.plotfillalpha);I=b(a.entityfillratio,a.fillratio,q.plotfillratio);K=b(a.entityfillangle,a.fillangle,q.plotfillangle);H=b(a.nullentityfillcolor,a.nullentitycolor,L);F=d(a.showcanvasborder,l)?d(a.canvasborderthickness,1):0;G(f,{chart:{emulateFlashGutter:d(a._emulateflashgutter,1),defaultSeriesType:this.defaultSeriesType,paletteIndex:q.index,borderRadius:d(a.canvasborderradius,0),borderColor:Z(b(a.canvasbordercolor,
q.canvasbordercolor),b(a.canvasborderalpha,q.canvasborderalpha)),borderWidth:F,borderDashStyle:d(a.canvasborderdashed,0)?wa(d(a.canvasborderdashlen,4),d(a.canvasborderdashgap,2),F):"none",backgroundColor:ba({color:J,alpha:p,angle:b(a.bgangle,a.canvasbgangle,q.canvasbgangle),ratio:b(a.bgratio,a.canvasbgratio,q.canvasbgratio)}),plotBorderColor:"#ffffff",plotBorderWidth:0,plotBackgroundColor:ba({color:"#ffffff",alpha:0}),bgSWF:b(a.bgimage,a.bgswf),bgSWFAlpha:d(a.bgimagealpha,a.bgswfalpha,100),bgImageScale:d(a.bgimagescale,
100),bgImageDisplayMode:b(a.bgimagedisplaymode,"none").toLowerCase(),logoURL:ua(a.logourl),logoPosition:b(a.logoposition,"tl").toLowerCase(),logoAlpha:d(a.logoalpha,100),logoLink:ua(a.logolink),logoScale:d(a.logoscale,100),logoLeftMargin:d(a.logoleftmargin,0),logoTopMargin:d(a.logotopmargin,0),toolbar:function(){var f={button:{}},g=f.button,k;g.scale=d(a.toolbarbuttonscale,1.15);g.width=d(a.toolbarbuttonwidth,15);g.height=d(a.toolbarbuttonheight,15);g.radius=d(a.toolbarbuttonradius,2);g.spacing=d(a.toolbarbuttonspacing,
5);g.fill=Z(b(a.toolbarbuttoncolor,"ffffff"));g.labelFill=Z(b(a.toolbarlabelcolor,"cccccc"));g.symbolFill=Z(b(a.toolbarsymbolcolor,"ffffff"));g.hoverFill=Z(b(a.toolbarbuttonhovercolor,"ffffff"));g.stroke=Z(b(a.toolbarbuttonbordercolor,"bbbbbb"));g.symbolStroke=Z(b(a.toolbarsymbolbordercolor,"9a9a9a"));g.strokeWidth=d(a.toolbarbuttonborderthickness,1);g.symbolStrokeWidth=d(a.toolbarsymbolborderthickness,1);k=g.symbolPadding=d(a.toolbarsymbolpadding,5);g.symbolHPadding=d(a.toolbarsymbolhpadding,k);
g.symbolVPadding=d(a.toolbarsymbolvpadding,k);k=f.position=b(a.toolbarposition,"tr").toLowerCase();switch(k){case "tr":case "tl":case "br":case "bl":break;default:k="tr"}g=f.hAlign="left"===(""+a.toolbarhalign).toLowerCase()?"l":k.charAt(1);k=f.vAlign="bottom"===(""+a.toolbarvalign).toLowerCase()?"b":k.charAt(0);f.hDirection=d(a.toolbarhdirection,"r"===g?-1:1);f.vDirection=d(a.toolbarvdirection,"b"===k?-1:1);f.vMargin=d(a.toolbarvmargin,6);f.hMargin=d(a.toolbarhmargin,10);f.x=d(a.toolbarx,"l"===g?
0:e);f.y=d(a.toolbary,"t"===k?0:c);return f}()},title:{text:ja(a.caption),offsetX:Number(a.captionxshift),offsetY:Number(a.captionyshift),position:b(a.captionposition,void 0!==a.captionxshift||void 0!==a.captionyshift?"top left":"top"),padding:d(a.captionpadding,10),style:{fontFamily:b(a.captionfontfamily,y),color:b(a.captionfontcolor,A).replace(/^#?([a-f0-9]+)/ig,"#$1"),fontSize:d(a.captionfontsize,u+3)+"px",fontWeight:0===d(a.captionfontbold)?"normal":"bold"}},subtitle:{text:ja(a.subcaption),style:{fontFamily:b(a.subcaptionfontfamily,
a.captionfontfamily,y),color:b(a.subcaptionfontcolor,a.captionfontcolor,A).replace(/^#?([a-f0-9]+)/ig,"#$1"),fontSize:d(a.subcaptionfontsize,d(sa(a.captionfontsize-3,1),u))+"px",fontWeight:0===d(a.subcaptionfontbold)?"normal":"bold"}},orphanStyles:{defaultStyle:{style:G({},k.inCanvasStyle)}},tooltip:{enabled:0!==k.showTooltip,style:{fontFamily:t,fontSize:w,lineHeight:B,color:r,padding:d(a.tooltippadding,this.tooltippadding,3)+"px",backgroundColor:Z(b(n.backgroundColor,a.tooltipbgcolor,q.tooltipbgcolor),
b(a.tooltipbgalpha,"100")),borderColor:Z(b(n.borderColor,a.tooltipbordercolor,q.tooltipbordercolor),b(a.tooltipborderalpha,"100")),borderWidth:d(a.tooltipborderthickness,l)+"px",borderRadius:d(a.tooltipborderradius,v+1)+"px"},constrain:d(a.constraintooltip,1),shadow:d(a.showtooltipshadow,a.showshadow,1)?{enabled:!0,opacity:sa(d(a.tooltipbgalpha,100),d(a.tooltipborderalpha,100))/100}:!1},legend:{itemStyle:{fontFamily:b(a.legenditemfont,y),fontSize:d(a.legenditemfontsize,u)+"px",color:Y(b(a.legenditemfontcolor,
A)),fontWeight:d(a.legenditemfontbold)?"bold":"normal"},itemHiddenStyle:{fontFamily:y,fontSize:x,color:Y(b(a.legenditemhiddencolor,A))},itemHoverStyle:{color:Y(b(a.legenditemhoverfontcolor,a.legenditemfontcolor,A))},enabled:d(a.showlegend,1),title:{text:ja(a.legendcaption),style:{fontFamily:b(a.legendcaptionfont,y),fontSize:d(a.legendcaptionfontsize,u)+"px",color:Y(b(a.legendcaptionfontcolor,A)),fontWeight:d(a.legendcaptionfontbold,1)?"bold":"normal"},align:R[b(a.legendcaptionalignment)]},position:b(a.legendposition,
0===d(g.colorrange&&g.colorrange.gradient,0)?"right":"bottom"),backgroundColor:b(a.legendbgcolor,q.bgcolor),backgroundAlpha:b(a.legendbgalpha,"100"),borderColor:b(a.legendbordercolor,q.legendbordercolor),borderThickness:b(a.legendborderthickness,"1"),borderAlpha:b(a.legendborderalpha,"100"),shadow:d(a.legendshadow,1),allowDrag:d(a.legendallowdrag,0),scroll:{scrollBgColor:b(a.legendscrollbgcolor,a.scrollcolor,"AAAAAA"),scrollBtnColor:b(a.legendscrollbtncolor,"BBBBBB"),scrollBarColor:b(a.legendscrollbarcolor,
"CCCCCC")},reversed:d(a.reverselegend,0),interactive:d(a.interactivelegend,0),minColor:H,lighting3d:m},markers:{dataLabels:{style:{fontFamily:b(a.markerfont,t),fontSize:d(a.markerfontsize,parseInt(w,10)),fontColor:b(a.markerfontcolor,r)}},showTooltip:d(a.showmarkertooltip,k.showTooltip),showLabels:d(a.showmarkerlabels,a.showlabels,1),showHoverEffect:d(a.showmarkerhovereffect,1),labelPadding:b(a.markerlabelpadding,"5"),labelWrapWidth:d(a.markerlabelwrapwidth,0),labelWrapHeight:d(a.markerlabelwrapheight,
0),fillColor:b(a.markerfillcolor,a.markerbgcolor,q.markerfillcolor),fillAlpha:b(a.markerfillalpha,q.markerfillalpha),fillAngle:b(a.markerfillangle,q.markerfillangle),fillRatio:b(a.markerfillratio,q.markerfillratio),fillPattern:b(a.markerfillpattern,q.markerbgpattern),hoverFillColor:a.markerfillhovercolor,hoverFillAlpha:a.markerfillhoveralpha,hoverFillRatio:a.markerfillhoverratio,hoverFillAngle:a.markerfillhoverangle,borderThickness:b(a.markerborderthickness,1),borderColor:b(a.markerbordercolor,q.markerbordercolor),
borderAlpha:d(a.markerborderalpha,q.markerborderalpha),hoverBorderThickness:a.markerborderhoverthickness,hoverBorderColor:a.markerborderhovercolor,hoverBorderAlpha:a.markerborderhoveralpha,radius:d(a.markerradius&&E.trimString(a.markerradius),7),shapeId:b(a.defaultmarkershape,"circle"),labelSepChar:b(a.labelsepchar,", "),tooltipSepChar:k.tooltipSepChar,autoScale:d(a.autoscalemarkers,0),tooltext:b(z&&z.tooltext,a.markertooltext),dataEnabled:k.useValuesForMarkers,valueToRadius:d(a.markerradiusfromvalue,
1),valueMarkerAlpha:b(a.valuemarkeralpha,"75"),hideNull:d(a.hidenullmarkers,0),nullRadius:d(a.nullmarkerradius,a.markerradius,7),adjustViewPort:d(a.adjustviewportformarkers,0),startAngle:d(a.markerstartangle,90),maxRadius:d(a.maxmarkerradius,0),minRadius:d(a.minmarkerradius,0),applyAll:d(a.applyallmarkers,0),shadow:d(a.showmarkershadow,a.showshadow,0)},connectors:{showHoverEffect:d(a.showconnectorhovereffect,1),thickness:d(a.connectorthickness,a.markerconnthickness,"2"),color:b(a.connectorcolor,a.markerconncolor,
q.markerbordercolor),alpha:b(a.connectoralpha,a.markerconnalpha,"100"),hoverthickness:d(a.connectorhoverthickness,a.connectorthickness,a.markerconnthickness,"2"),hovercolor:b(a.connectorhovercolor,a.connectorcolor,a.markerconncolor,q.markerbordercolor),hoveralpha:b(a.connectorhoveralpha,a.connectoralpha,a.markerconnalpha,"100"),dashed:d(a.connectordashed,a.markerconndashed,0),dashLen:d(a.connectordashlen,a.markerconndashlen,3),dashGap:d(a.connectordashgap,a.markerconndashgap,2),font:b(a.connectorfont,
a.markerconnfont,t),fontColor:b(a.connectorfontcolor,a.markerconnfontcolor,r),fontSize:d(a.connectorfontsize,a.markerconnfontsize,parseInt(w,10)),showLabels:d(a.showconnectorlabels,a.showmarkerlabels,a.showlabels,1),labelBgColor:b(a.connectorlabelbgcolor,a.markerconnlabelbgcolor,q.plotfillcolor),labelBorderColor:b(a.connectorlabelbordercolor,a.markerconnlabelbordercolor,q.markerbordercolor),shadow:d(a.showconnectorshadow,a.showmarkershadow,a.showshadow,0),showTooltip:d(a.showconnectortooltip,a.showmarkertooltip,
k.showTooltip),tooltext:b(z&&z.connectortooltext,a.connectortooltext),hideOpen:d(a.hideopenconnectors,1)},entities:{baseScaleFactor:this.baseScaleFactor,dataLabels:{style:{fontFamily:t,fontSize:w,lineHeight:B,color:f.plotOptions.series.dataLabels.color=r}},fillColor:L,fillAlpha:P,fillRatio:I,fillAngle:K,borderColor:D,borderAlpha:b(a.entityborderalpha,a.borderalpha,this.borderAlpha,"100"),borderThickness:d(a.showentityborder,a.showborder,1)?d(a.entityborderthickness,a.borderthickness,1):0,scaleBorder:d(a.scaleentityborder,
a.scaleborder,0),hoverFillColor:b(a.entityfillhovercolor,a.hoverfillcolor,a.hovercolor,q.plothoverfillcolor),hoverFillAlpha:b(a.entityfillhoveralpha,a.hoverfillalpha,a.hoveralpha,q.plothoverfillalpha),hoverFillRatio:b(a.entityfillhoverratio,a.hoverfillratio,a.hoverratio,q.plothoverfillratio),hoverFillAngle:b(a.entityfillhoverangle,a.hoverfillangle,a.hoverangle,q.plothoverfillangle),hoverBorderThickness:b(a.entityborderhoverthickness,a.hoverborderthickness),hoverBorderColor:b(a.entityborderhovercolor,
q.plotbordercolor),hoverBorderAlpha:b(a.entityborderhoveralpha,q.plotborderalpha),nullEntityColor:H,nullEntityAlpha:b(a.nullentityfillalpha,a.nullentityalpha,P),nullEntityRatio:b(a.nullentityfillratio,a.nullentityratio,I),nullEntityAngle:b(a.nullentityfillangle,a.nullentityangle,K),connectorColor:b(a.labelconnectorcolor,a.connectorcolor,r),connectorAlpha:b(a.labelconnectoralpha,a.connectoralpha,"100"),connectorThickness:d(a.labelconnectorthickness,a.borderthickness,1),showHoverEffect:d(a.showentityhovereffect,
a.usehovercolor,k.showHoverEffect),hoverOnNull:d(a.hoveronnull,a.entityhoveronnull,1),labelPadding:d(a.labelpadding,5),showLabels:d(a.showlabels,1),labelsOnTop:d(a.entitylabelsontop,1),includeNameInLabels:d(a.includenameinlabels,1),includeValueInLabels:d(a.includevalueinlabels,0),useSNameInTooltip:d(a.usesnameintooltip,0),useShortName:d(a.usesnameinlabels,1),labelSepChar:b(a.labelsepchar,", "),showTooltip:d(a.showentitytooltip,k.showTooltip),tooltipSepChar:k.tooltipSepChar,tooltext:a.entitytooltext,
hideNullEntities:d(a.hidenullentities,0),showHiddenEntityBorder:d(a.showhiddenentityborder,1),showNullEntityBorder:d(a.shownullentityborder,1),hiddenEntityColor:b(a.hiddenentitycolor,a.hiddenentityfillcolor,a.hiddenentityalpha||a.hiddenentityfillalpha?H:"ffffff"),hiddenEntityAlpha:b(a.hiddenentityalpha,a.hiddenentityfillalpha,.001),shadow:d(a.showshadow,this.defaultPlotShadow,q.shadow)},entitydef:{useSNameAsId:d(a.usesnameasid,0)}});f.legend.title.style.lineHeight=fa(f.legend.title.style);f.legend.itemStyle.lineHeight=
fa(f.legend.itemStyle);f.legend.itemHiddenStyle.lineHeight=fa(f.legend.itemHiddenStyle);z=Da(e,c,a.markermaxradius,a.markerminradius);f.markers.maxRadius=z.max;f.markers.minRadius=z.min;a.tooltipcolor&&(f.tooltip.style.color=ka(a.tooltipcolor));void 0!==b(a.clickurl)&&(h.link=a.clickurl,h.style.cursor="pointer",oa&&(h.style._cursor="hand"),f.plotOptions.series.point.events.click=function(){h.events.click.call({link:a.clickurl})});z=h.bgImageDisplayMode;k=ua(a.bgimagevalign,"").toLowerCase();v=ua(a.bgimagehalign,
"").toLowerCase();"tile"==z||"fill"==z||"fit"==z?("top"!=k&&"middle"!=k&&"bottom"!=k&&(k="middle"),"left"!=v&&"middle"!=v&&"right"!=v&&(v="middle")):("top"!=k&&"middle"!=k&&"bottom"!=k&&(k="top"),"left"!=v&&"middle"!=v&&"right"!=v&&(v="left"));h.bgImageVAlign=k;h.bgImageHAlign=v;this.parseStyles(f);fa(f.title.style);fa(f.subtitle.style);fa(f.tooltip.style);f.plotOptions.series.allowPointSelect=!0;this.parseExportOptions(f);this.preSeriesAddition&&this.preSeriesAddition(f,g,e,c);this.series&&this.series(g,
f,this.name,e,c);this.postSeriesAddition&&this.postSeriesAddition(f,g,e,c);this.spaceManager(f,g,e,c);X.console&&X.FC_DEV_ENVIRONMENT&&X.console.log(f);return f},series:function(e,c){function g(b){for(D=b&&b.length||0;D--;)y=b[D],p=y.value,y.cleanValue=a.getCleanValue(p),y.formattedValue=null!==y.cleanValue?a.dataLabels(p):void 0,y.origValue=p,null!==y.cleanValue&&(r=Q(y.cleanValue,r),u=sa(y.cleanValue,u))}function f(a,e,f){for(D=a&&a.length||0;D--;){y=a[D];var g;a:{g=d(y.value);for(var h=void 0,
z=void 0,h=void 0,p=J&&J.length||0;p--;)if(h=J[p],z=Number(h.maxvalue),h=d(h.minvalue,c.colorRange.scaleMin),g>=h&&g<=z){g=p;break a}g=null}F=g;null!==F&&(H="gradient"===w.type?c.colorRange.getColorObj(y.value).code:q&&q[F]&&b(q[F].color,q[F].code),x[F]||(x[F]=[]),H&&(y.color=y.color?y.color:H,e&&(y.alpha=y.alpha?y.alpha:e),f&&(m||y.fillhoveralpha||(y.fillhoveralpha=y.alpha),k||y.fillhovercolor||(y.fillhovercolor=y.color)),x[F].push(y)))}}var a=this.numberFormatter,h=this.hcJSON.series,l=c.markers.valueMarkerAlpha,
k=c.markers.hasHoverColor,m=c.markers.hasHoverAlpha,v=this.dataObj,n=c[ra],t=v.colorrange,q=t&&t.color,w=c.legend,x={},t={legendClick:function(){var a;if(a=this.chart)!this.legend&&(this.legend=this.plot.legend),a.legendClick(this,!this.visible)},getEventArgs:function(){var a;if(a=this.chart)return!this.legend&&(this.legend=this.plot.legend),a.getEventArgs(this)},setVisible:function(a){var b=this.data,e=this.legendItem,c=this.visible;this.visible=a=void 0===a?!c:a;e&&w.colorizeItem&&w.colorizeItem(this,
a);for(c=b&&b.length;c--;)(e=b[c].mapItem)&&(a?e.show&&e.show():e.hide&&e.hide())}},r=Infinity,u=-Infinity,y,H,A,J,p,F,B,D;g(v.data||[]);n.useValuesForMarkers&&g(v.markers&&v.markers.items||[]);n._doNotShowLegend=!0;w.type=v.colorrange&&"1"===v.colorrange.gradient?"gradient":"point";Infinity===r&&(r=void 0);-Infinity===u&&(u=void 0);n.dataMin=r;n.dataMax=u;c.colorRange=new E.colorRange({colorRange:v.colorrange,dataMin:r,dataMax:u,defaultColor:w.minColor,numberFormatter:a});D=(J=c.colorRange.colorArr)&&
J.length||0;if(0<D){for(;D--;)A=J[D],!n._doNotShowLegend||""===A.label&&void 0===A.label||(n._doNotShowLegend=!1),h.push(G({type:this.defaultSeriesType,showInLegend:!0,data:[],plot:{},name:A.label,color:A.code,rangeMin:A.minvalue,rangeMax:A.maxvalue,visible:!0},t));f(v.data||[]);n.useValuesForMarkers&&f(v.markers&&v.markers.items||[],l,!0);h=h.reverse();for(B in x)h[B]&&(h[B].data=x[B])}else h.push({type:this.defaultSeriesType,data:[]});n._doNotShowLegend&&(this.hcJSON.legend.enabled=!1)},preliminaryScaling:function(b,
c){for(var g=c.markers&&c.markers.items||[],f=g&&g.length||0,a=Infinity,d=Infinity,h=-Infinity,k=-Infinity,l,v;f--;)v=g[f],l=Number(v.x),v=Number(v.y),a=Q(a,l),d=Q(d,v),h=sa(h,l),k=sa(k,v);return{x:a,y:d,x1:h,y1:k}},getScalingParameters:function(b,c,g,f){var a=b/c,d=g/(b*this.baseScaleFactor),h=f/(c*this.baseScaleFactor),k=0,l=0;d>h?(d=h,k+=(g-f*a)/2,b=200/(c*d)):(l+=(f-g/a)/2,b=200/(b*d));return{scaleFactor:d,strokeWidth:b,translateX:k,translateY:l}},calculateMarkerBounds:function(b,c,g,f,a){var d=
b.markers,h=b[ra];b=h.dataMin;for(var h=h.dataMax,k=d.minRadius,l=d.maxRadius,v=d.hideNull,m=d.nullRadius,d=d.valueToRadius,n=(c=c.markers&&c.markers.items||[],c.length)||0,q=Infinity,t=Infinity,w=-Infinity,r=-Infinity,u,y,x;n--;)y=c[n],null!==y.cleanValue?(d&&void 0===y.radius&&(y.radius=k+(l-k)*(y.cleanValue-b)/(h-b)),x=Number(y.radius),u=(Number(y.x)+f)*g,y=(Number(y.y)+a)*g,q=Q(q,u-x),t=Q(t,y-x),w=sa(w,u+x),r=sa(r,y+x)):v?y.__hideMarker=!0:void 0===y.radius&&(y.radius=m);return{x:q,y:t,x1:w,y1:r}},
spaceManager:function(b,c,g,f){var a=b.chart,d=b[ra],h=a.spacingLeft,k=a.spacingTop,l=this.baseWidth,v=this.baseHeight;g-=a.spacingRight+h;a=f-(a.spacingBottom+k);f=d._captionBlock=this.manageTitleSpace(b,c,g,a);var m=d._legendBlock=this.placeLegendBlock(b,c,g,a-f.height,f.isBottom?f.height:0);g-=m.width;var a=a-f.height-m.height,n=m=0;d.useValuesForMarkers?(d.adjustViewPortForMarkers?(d=this.preliminaryScaling(b,c),d.x1>l&&(l=d.x1),0>d.x&&(l+=-d.x,n=-d.x),d.y1>v&&(v=d.y1),0>d.y&&(v+=-d.y,m=-d.y),
d=this.getScalingParameters(l,v,g,a),d=this.calculateMarkerBounds(b,c,d.scaleFactor*this.baseScaleFactor,n,m),b=a,c=g,0>d.x&&(h+=-d.x,g+=d.x),0>d.y&&(k+=-d.y,a+=d.y),d.x1>c&&(g-=d.x1-c),d.y1>b&&(a-=d.y1-b)):(d=this.getScalingParameters(l,v,g,a),this.calculateMarkerBounds(b,c,d.scaleFactor*this.baseScaleFactor,n,m)),d=this.getScalingParameters(l,v,g,a),h+=n*d.scaleFactor*this.baseScaleFactor,k+=m*d.scaleFactor*this.baseScaleFactor):d=this.getScalingParameters(l,v,g,a);/bottom/i.test(f.position)||(k+=
f.height);this.scaleFactor=d.scaleFactor;this.strokeWidth=d.strokeWidth;this.translateX=d.translateX+h;this.translateY=d.translateY+k},placeGLegendBlockRight:E.placeGLegendBlockRight,placeGLegendBlockBottom:E.placeGLegendBlockBottom,placeLegendBlock:function(b,c,d,f,a){var h=b.legend,l=b[ra],k=h.position.toLowerCase(),m={position:k};if("0"===c.chart.showlegend||l._doNotShowLegend)return m.height=0,m.width=0,m;"bottom"===k?(m.height="gradient"===h.type?this.placeGLegendBlockBottom(b,c,d,f):this.placeLegendBlockBottom(b,
c,d,f),m.width=0,a&&(h.y=-a)):(d/=2,m.width="gradient"===h.type?this.placeGLegendBlockRight(b,c,d,f):this.placeLegendBlockRight(b,c,d,f),m.height=0);return m},manageTitleSpace:function(b,c,d,f){var a=this.hcJSON;b=a.title;c=a.chart;var a=a.subtitle,h=this.smartLabel,l=f/2,k=0,m=b.position.toLowerCase(),n=b.padding,t=!1,w=b.offsetX,q=b.offsetY,x=0,E={},r,u;if(""===b.text&&""===a.text)return{height:0,position:m};isNaN(w)&&isNaN(q)||(t=!0,w=isNaN(w)?0:w,q=isNaN(q)?0:q);r=b.text;if(""!==r){h.setStyle(b.style);
u=h.getOriSize(r);if(u.width>d||u.height>l)u=h.getSmartText(r,d,l),b.text=u.text,u.tooltext&&(b.originalText=u.tooltext);b.height=x=u.height;k+=x}l-=k;r=a.text;if(""!==r){h.setStyle(a.style);u=h.getOriSize(r);if(u.width>d||u.height>l)u=h.getSmartText(r,d,l),a.text=u.text,u.tooltext&&(a.originalText=u.tooltext);k+=a.height=u.height}k=k+n>l?l:k+n;m.match(/left/)?(a.align=b.align="start",a.x=b.x=c.marginLeft):m.match(/right/)?(a.align=b.align="end",a.x=b.x=d):(a.align=b.align="middle",a.x=b.x=d/2);/bottom/.test(m)?
(d=f-k+c.marginTop+n,b.y=d,a.y=d+x,t?(b.y+=q,a.y+=q,b.x+=w,a.x+=w):(c.marginBottom+=k,E.isBottom=!0)):t?(b.y+=q,a.y+=q,b.x+=w,a.x+=w):c.marginTop+=k;E.height=t?0:k;E.position=m;return E},getFirstId:function(){return this.firstEntity},getEntityPaths:function(b){var c={},d=this.entities,f;if(b){for(f in d)c[f]=d[f];return c}return d},redefineEntities:function(b,c){var d=this.entities,f={},a={},h=0,l,k,m,n,t,w,q,x;for(q=b.length;q--;)if(l=b[q],k=l.internalid,t=l.newid?l.newid:k,m=l.sname,l=l.lname,n=
d[k],k=E.trimString(k),t=E.trimString(t),n){f[t]=t={origId:k};a[k]=!0;for(w in n)t[w]=n[w];t.shortLabel=m?m:n.shortLabel;t.label=l?l:n.label}this.entities={};for(x in f)f[x].origId=x,this.entities[x.toLowerCase()]=f[x],h+=1;for(x in d)if(t=d[x],x=E.trimString(x),!a[x]){c.useSNameAsId?(this.entities[t.shortLabel.toLowerCase()]=n={},n.origId=t.shortLabel):(this.entities[x.toLowerCase()]=n={},n.origId=x);for(w in t)n[w]=t[w];h+=1}this.entityCount=h},colorPaletteMap:{basefontcolor:"foregroundcolor",bordercolor:"foregrounddarkcolor",
borderalpha:"foregrounddarkalpha",bgcolor:"backgroundlightcolor",bgalpha:"backgroundlightalpha",bgangle:"backgroundlightangle",bgratio:"backgroundlightratio",canvasbordercolor:"foregrounddarkcolor",canvasborderalpha:"foregrounddarkalpha",canvasbgcolor:"backgroundlightcolor",canvasbgalpha:"backgroundlightalpha",canvasbgangle:"backgroundlightangle",canvasbgratio:"backgroundlightratio",tooltipbordercolor:"foregrounddarkcolor",tooltipborderalpha:"foregrounddarkalpha",tooltipbgcolor:"backgroundlightcolor",
tooltipbgalpha:"backgroundlightalpha",tooltipfontcolor:"foregroundcolor",legendbordercolor:"foregrounddarkcolor",legendborderalpha:"foregrounddarkalpha",markerbordercolor:"foregroundlightcolor",markerborderalpha:"foregroundlightalpha",markerfillcolor:"backgrounddarkcolor",markerfillalpha:"backgrounddarkalpha",markerfillangle:"backgrounddarkangle",markerfillratio:"backgrounddarkratio",plotfillcolor:"backgroundcolor",plotfillalpha:"backgroundalpha",plotfillangle:"backgroundangle",plotfillratio:"backgroundratio",
plothoverfillcolor:"backgrounddarkcolor",plothoverfillalpha:"backgrounddarkalpha",plothoverfillangle:"backgrounddarkangle",plothoverfillratio:"backgrounddarkratio",plotbordercolor:"foregroundcolor",plotborderalpha:"foregroundalpha",shadow:"shadow"},eiMethods:{getMapName:function(){return this.jsVars.hcObj.logic.name},getEntityList:function(){var b=this.jsVars.hcObj,b=b.entities&&b.entities.items,c,d=[],f,a;for(f in b)a=b[f],c=a.eJSON,d.push({id:a.id,originalId:a.originalId||a.id,label:c.label,shortlabel:c.shortLabel,
value:a.value,formattedValue:a.formattedValue,toolText:a.toolText});return d},getDataAsCSV:function(){var b=this.jsVars,b=b.hcObj&&b.hcObj.entities&&b.hcObj.entities.items,c='"Id","Short Name","Long Name","Value","Formatted Value"',d,f,a,h;for(d in b)f=b[d],a=f.eJSON,h=f.value,c+='\r\n"'+f.id+'","'+a.shortLabel+'","'+a.label+'","'+(void 0===h?"":h)+'","'+f.formattedValue+'"';return c},getMapAttribute:function(){var b=this.jsVars.fcObj;V.raiseWarning(this,"12061210581","run","JavaScriptRenderer~getMapAttribute()",
'Use of deprecated "getMapAttribute()". Replace with "getChartAttribute()".');return b.getChartAttribute.apply(b,arguments)},exportMap:function(){var b=this.jsVars.fcObj;V.raiseWarning(this,"12061210581","run","JavaScriptRenderer~exportMap()",'Use of deprecated "exportMap()". Replace with "exportChart()".');return b.exportChart&&b.exportChart.apply(b,arguments)},addMarker:function(b){this.jsVars.hcObj.markers.addMarkerItem(b)||V.raiseWarning(this,"1309264086","run","MapsRenderer~addMarker()","Failed to add marker. Check the options and try again.")},
updateMarker:function(b,c){var d=this.jsVars.hcObj,f=d.markers,d=d.mapAnnotations,a;b&&(b=(b+"").toLowerCase(),f=f.items[b])&&(a=f.options,G(a,c),f=f.draw().markerShape,d.update(b,f))},removeMarker:function(b){var c=this.jsVars.hcObj.markers,d;b&&(b=(b+"").toLowerCase(),(d=c.items[b])&&d.destroy(),delete c.items[b])}}},aa.linebase);aa("renderer.maps",{drawGraph:function(){var b=this,c=b.logic.chartInstance,d=b.paper,f=b.layers,a,h,l;b.options.nativeMessage||(f.dataset||(f.dataset=d.group("dataset").insertAfter(f.background),
f.tracker=d.group("hot").insertAfter(f.dataset)),b.shadowLayer||(b.shadowLayer=f.shadow=d.group("shadow").insertBefore(f.dataset)),xa||(f.dataset&&f.dataset.hide(),f.shadow&&f.shadow.hide()),b.strokeWidth=b.logic.strokeWidth,a=b.logic.scaleFactor,b.translateX=h=b.logic.translateX,b.translateY=l=b.logic.translateY,b.sFactor=a*b.logic.baseScaleFactor,b.transformStr=["t",h,",",l,"s",a,",",a,",0,0"].join(""),b.options.tooltip&&!1!==b.options.tooltip.enabled&&d.tooltip(b.options.tooltip.style,b.options.tooltip.shadow,
b.options.tooltip.constrain),b.mapAnnotations=new E.Annotations,b.mapAnnotations.reset(null,{id:"geo",showbelow:0,autoscale:0,grpxshift:b.translateX?b.translateX:0,grpyshift:b.translateY?b.translateY:0,xscale:100*(b.sFactor?b.sFactor:1),yscale:100*(b.sFactor?b.sFactor:1),options:{useTracker:!0}}),b.processEntityDefs(),b.drawEntities(),c.addEventListener("internal.mapdrawingcomplete",function(a){a.detachHandler();xa?(f.dataset&&f.dataset.attr({transform:b.transformStr}),f.shadow&&f.shadow.attr({transform:b.transformStr})):
(f.dataset&&f.dataset.show(),f.shadow&&f.shadow.show())}),b.drawMarkers())},setScaleRange:function(b,c){for(var d=this.options.series,f=d.length,a,h,l,k;f--;)if(l=d[f],h=(a=l.data)&&a.length)if(l.rangeMin>=b&&l.rangeMax<=c)l.setVisible(!0);else if(l.rangeMax<b||l.rangeMin>c)l.setVisible(!1);else for(;h--;)l=(k=a[h].mapItem)&&k.value,isNaN(l)||""===l||(l>=b&&l<=c?k.show():k.hide())},processEntityDefs:function(){var b=this.logic,c=this.options.series,d=c&&c.length;for(b.redefineEntities(b.dataObj.entitydef||
[],this.options.entitydef);d--;)c[d].chart=this},drawEntities:function(){this.entities=new n(this.logic&&this.logic.dataObj&&this.logic.dataObj.data,this,this.logic,this.layers.dataset)},drawMarkers:function(){var b=this.logic&&this.logic.dataObj&&this.logic.dataObj.markers||null;b&&(this.markers=new w(b,this,this.group));this.options.entities.labelsOnTop||this.entities.drawLabels()},checkComplete:function(){var b=this.logic,c=b.chartInstance;this.entities&&this.entities.isReady()&&(this.mapAnnotations.draw(this),
b.hasRendered=!0,V.raiseEvent("internal.mapdrawingcomplete",{renderer:this},c))}},aa["renderer.root"])},[3,2,0,"release"]]);
